// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package LPMsg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PathNode struct {
	Sertype              int32    `protobuf:"varint,1,opt,name=sertype,proto3" json:"sertype,omitempty"`
	Serid                int32    `protobuf:"varint,2,opt,name=serid,proto3" json:"serid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PathNode) Reset()         { *m = PathNode{} }
func (m *PathNode) String() string { return proto.CompactTextString(m) }
func (*PathNode) ProtoMessage()    {}
func (*PathNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

func (m *PathNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PathNode.Unmarshal(m, b)
}
func (m *PathNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PathNode.Marshal(b, m, deterministic)
}
func (m *PathNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PathNode.Merge(m, src)
}
func (m *PathNode) XXX_Size() int {
	return xxx_messageInfo_PathNode.Size(m)
}
func (m *PathNode) XXX_DiscardUnknown() {
	xxx_messageInfo_PathNode.DiscardUnknown(m)
}

var xxx_messageInfo_PathNode proto.InternalMessageInfo

func (m *PathNode) GetSertype() int32 {
	if m != nil {
		return m.Sertype
	}
	return 0
}

func (m *PathNode) GetSerid() int32 {
	if m != nil {
		return m.Serid
	}
	return 0
}

type ReqNoticeServer struct {
	ServerType           int32       `protobuf:"varint,1,opt,name=serverType,proto3" json:"serverType,omitempty"`
	Path                 []*PathNode `protobuf:"bytes,2,rep,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ReqNoticeServer) Reset()         { *m = ReqNoticeServer{} }
func (m *ReqNoticeServer) String() string { return proto.CompactTextString(m) }
func (*ReqNoticeServer) ProtoMessage()    {}
func (*ReqNoticeServer) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

func (m *ReqNoticeServer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqNoticeServer.Unmarshal(m, b)
}
func (m *ReqNoticeServer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqNoticeServer.Marshal(b, m, deterministic)
}
func (m *ReqNoticeServer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqNoticeServer.Merge(m, src)
}
func (m *ReqNoticeServer) XXX_Size() int {
	return xxx_messageInfo_ReqNoticeServer.Size(m)
}
func (m *ReqNoticeServer) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqNoticeServer.DiscardUnknown(m)
}

var xxx_messageInfo_ReqNoticeServer proto.InternalMessageInfo

func (m *ReqNoticeServer) GetServerType() int32 {
	if m != nil {
		return m.ServerType
	}
	return 0
}

func (m *ReqNoticeServer) GetPath() []*PathNode {
	if m != nil {
		return m.Path
	}
	return nil
}

type AckNoticeServer struct {
	State                int32    `protobuf:"varint,1,opt,name=state,proto3" json:"state,omitempty"`
	Sertype              int32    `protobuf:"varint,2,opt,name=sertype,proto3" json:"sertype,omitempty"`
	Serid                []int32  `protobuf:"varint,3,rep,packed,name=serid,proto3" json:"serid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AckNoticeServer) Reset()         { *m = AckNoticeServer{} }
func (m *AckNoticeServer) String() string { return proto.CompactTextString(m) }
func (*AckNoticeServer) ProtoMessage()    {}
func (*AckNoticeServer) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{2}
}

func (m *AckNoticeServer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AckNoticeServer.Unmarshal(m, b)
}
func (m *AckNoticeServer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AckNoticeServer.Marshal(b, m, deterministic)
}
func (m *AckNoticeServer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AckNoticeServer.Merge(m, src)
}
func (m *AckNoticeServer) XXX_Size() int {
	return xxx_messageInfo_AckNoticeServer.Size(m)
}
func (m *AckNoticeServer) XXX_DiscardUnknown() {
	xxx_messageInfo_AckNoticeServer.DiscardUnknown(m)
}

var xxx_messageInfo_AckNoticeServer proto.InternalMessageInfo

func (m *AckNoticeServer) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *AckNoticeServer) GetSertype() int32 {
	if m != nil {
		return m.Sertype
	}
	return 0
}

func (m *AckNoticeServer) GetSerid() []int32 {
	if m != nil {
		return m.Serid
	}
	return nil
}

type RoomState struct {
	State                int32    `protobuf:"varint,1,opt,name=state,proto3" json:"state,omitempty"`
	Id                   int32    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Ip                   string   `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 int32    `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomState) Reset()         { *m = RoomState{} }
func (m *RoomState) String() string { return proto.CompactTextString(m) }
func (*RoomState) ProtoMessage()    {}
func (*RoomState) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{3}
}

func (m *RoomState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomState.Unmarshal(m, b)
}
func (m *RoomState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomState.Marshal(b, m, deterministic)
}
func (m *RoomState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomState.Merge(m, src)
}
func (m *RoomState) XXX_Size() int {
	return xxx_messageInfo_RoomState.Size(m)
}
func (m *RoomState) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomState.DiscardUnknown(m)
}

var xxx_messageInfo_RoomState proto.InternalMessageInfo

func (m *RoomState) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *RoomState) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RoomState) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *RoomState) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type RoomStateList struct {
	List                 []*RoomState `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RoomStateList) Reset()         { *m = RoomStateList{} }
func (m *RoomStateList) String() string { return proto.CompactTextString(m) }
func (*RoomStateList) ProtoMessage()    {}
func (*RoomStateList) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{4}
}

func (m *RoomStateList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomStateList.Unmarshal(m, b)
}
func (m *RoomStateList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomStateList.Marshal(b, m, deterministic)
}
func (m *RoomStateList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomStateList.Merge(m, src)
}
func (m *RoomStateList) XXX_Size() int {
	return xxx_messageInfo_RoomStateList.Size(m)
}
func (m *RoomStateList) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomStateList.DiscardUnknown(m)
}

var xxx_messageInfo_RoomStateList proto.InternalMessageInfo

func (m *RoomStateList) GetList() []*RoomState {
	if m != nil {
		return m.List
	}
	return nil
}

type BattleCheckData struct {
	Error                bool     `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Winer                int32    `protobuf:"varint,2,opt,name=winer,proto3" json:"winer,omitempty"`
	Star                 int32    `protobuf:"varint,3,opt,name=star,proto3" json:"star,omitempty"`
	Success              bool     `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	Md5                  string   `protobuf:"bytes,5,opt,name=md5,proto3" json:"md5,omitempty"`
	Achieve              int32    `protobuf:"varint,6,opt,name=achieve,proto3" json:"achieve,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BattleCheckData) Reset()         { *m = BattleCheckData{} }
func (m *BattleCheckData) String() string { return proto.CompactTextString(m) }
func (*BattleCheckData) ProtoMessage()    {}
func (*BattleCheckData) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{5}
}

func (m *BattleCheckData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BattleCheckData.Unmarshal(m, b)
}
func (m *BattleCheckData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BattleCheckData.Marshal(b, m, deterministic)
}
func (m *BattleCheckData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BattleCheckData.Merge(m, src)
}
func (m *BattleCheckData) XXX_Size() int {
	return xxx_messageInfo_BattleCheckData.Size(m)
}
func (m *BattleCheckData) XXX_DiscardUnknown() {
	xxx_messageInfo_BattleCheckData.DiscardUnknown(m)
}

var xxx_messageInfo_BattleCheckData proto.InternalMessageInfo

func (m *BattleCheckData) GetError() bool {
	if m != nil {
		return m.Error
	}
	return false
}

func (m *BattleCheckData) GetWiner() int32 {
	if m != nil {
		return m.Winer
	}
	return 0
}

func (m *BattleCheckData) GetStar() int32 {
	if m != nil {
		return m.Star
	}
	return 0
}

func (m *BattleCheckData) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *BattleCheckData) GetMd5() string {
	if m != nil {
		return m.Md5
	}
	return ""
}

func (m *BattleCheckData) GetAchieve() int32 {
	if m != nil {
		return m.Achieve
	}
	return 0
}

func init() {
	proto.RegisterType((*PathNode)(nil), "LPMsg.PathNode")
	proto.RegisterType((*ReqNoticeServer)(nil), "LPMsg.ReqNoticeServer")
	proto.RegisterType((*AckNoticeServer)(nil), "LPMsg.AckNoticeServer")
	proto.RegisterType((*RoomState)(nil), "LPMsg.RoomState")
	proto.RegisterType((*RoomStateList)(nil), "LPMsg.RoomStateList")
	proto.RegisterType((*BattleCheckData)(nil), "LPMsg.BattleCheckData")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206) }

var fileDescriptor_555bd8c177793206 = []byte{
	// 331 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xcb, 0x4e, 0xeb, 0x30,
	0x10, 0x86, 0x95, 0x5b, 0x4f, 0x3b, 0xe7, 0x1c, 0x52, 0x59, 0x2c, 0xbc, 0x42, 0x51, 0x60, 0xd1,
	0x55, 0x17, 0xa0, 0x6e, 0xd8, 0x71, 0x59, 0x96, 0xaa, 0x72, 0xb9, 0xac, 0x8d, 0x33, 0x22, 0x56,
	0x9b, 0x3a, 0xd8, 0xa6, 0x88, 0x27, 0xe1, 0x75, 0x51, 0x26, 0x4d, 0x5b, 0x24, 0xd8, 0xcd, 0x37,
	0x9e, 0xfc, 0xfa, 0x66, 0x14, 0xf8, 0xa7, 0x4c, 0x55, 0x99, 0xf5, 0xb8, 0xb6, 0xc6, 0x1b, 0x96,
	0x4c, 0xe7, 0x77, 0xee, 0x25, 0xbf, 0x84, 0xfe, 0x5c, 0xfa, 0x72, 0x66, 0x0a, 0x64, 0x1c, 0xfe,
	0x38, 0xb4, 0xfe, 0xa3, 0x46, 0x1e, 0x64, 0xc1, 0x28, 0x11, 0x1d, 0xb2, 0x63, 0x48, 0x1c, 0x5a,
	0x5d, 0xf0, 0x90, 0xfa, 0x2d, 0xe4, 0x8f, 0x90, 0x0a, 0x7c, 0x9d, 0x19, 0xaf, 0x15, 0x2e, 0xd0,
	0x6e, 0xd0, 0xb2, 0x13, 0x00, 0x47, 0xd5, 0xfd, 0x3e, 0xe5, 0xa0, 0xc3, 0x4e, 0x21, 0xae, 0xa5,
	0x2f, 0x79, 0x98, 0x45, 0xa3, 0xbf, 0xe7, 0xe9, 0x98, 0x24, 0xc6, 0x9d, 0x81, 0xa0, 0xc7, 0xfc,
	0x09, 0xd2, 0x2b, 0xb5, 0xfc, 0x96, 0xdb, 0x08, 0x78, 0xe9, 0xbb, 0xc8, 0x16, 0x0e, 0x85, 0xc3,
	0x5f, 0x84, 0xa3, 0x2c, 0xda, 0x0b, 0x3f, 0xc0, 0x40, 0x18, 0x53, 0x2d, 0xe8, 0xe3, 0x9f, 0x23,
	0x8f, 0x20, 0xdc, 0xad, 0x19, 0xea, 0x82, 0xb8, 0xe6, 0x51, 0x16, 0x8c, 0x06, 0x22, 0xd4, 0x35,
	0x63, 0x10, 0xd7, 0xc6, 0x7a, 0x1e, 0xd3, 0x04, 0xd5, 0xf9, 0x04, 0xfe, 0xef, 0x62, 0xa7, 0xda,
	0x79, 0x76, 0x06, 0xf1, 0x4a, 0x3b, 0xcf, 0x03, 0xda, 0x72, 0xb8, 0xdd, 0x72, 0x37, 0x23, 0xe8,
	0x35, 0xff, 0x0c, 0x20, 0xbd, 0x96, 0xde, 0xaf, 0xf0, 0xa6, 0x44, 0xb5, 0xbc, 0x95, 0x5e, 0x36,
	0x52, 0x68, 0xad, 0xb1, 0x24, 0xd5, 0x17, 0x2d, 0x34, 0xdd, 0x77, 0xbd, 0x46, 0xdb, 0x9d, 0x9f,
	0xa0, 0x51, 0x71, 0x5e, 0x5a, 0x92, 0x4b, 0x04, 0xd5, 0x74, 0x91, 0x37, 0xa5, 0xd0, 0x39, 0x32,
	0xec, 0x8b, 0x0e, 0xd9, 0x10, 0xa2, 0xaa, 0x98, 0xf0, 0x84, 0x36, 0x69, 0xca, 0x66, 0x56, 0xaa,
	0x52, 0xe3, 0x06, 0x79, 0xaf, 0xbd, 0xde, 0x16, 0x9f, 0x7b, 0xf4, 0x8b, 0x5c, 0x7c, 0x05, 0x00,
	0x00, 0xff, 0xff, 0x6a, 0x78, 0x62, 0x2f, 0x32, 0x02, 0x00, 0x00,
}
