// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dbdata.proto

package LPMsg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DBPlayerNumInfo struct {
	Dbid                 int32    `protobuf:"varint,1,opt,name=dbid,proto3" json:"dbid,omitempty"`
	Num                  int32    `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	Maxnum               int32    `protobuf:"varint,3,opt,name=maxnum,proto3" json:"maxnum,omitempty"`
	AccountTable         int32    `protobuf:"varint,4,opt,name=account_table,json=accountTable,proto3" json:"account_table,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBPlayerNumInfo) Reset()         { *m = DBPlayerNumInfo{} }
func (m *DBPlayerNumInfo) String() string { return proto.CompactTextString(m) }
func (*DBPlayerNumInfo) ProtoMessage()    {}
func (*DBPlayerNumInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_88e703bb8c3f1871, []int{0}
}

func (m *DBPlayerNumInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBPlayerNumInfo.Unmarshal(m, b)
}
func (m *DBPlayerNumInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBPlayerNumInfo.Marshal(b, m, deterministic)
}
func (m *DBPlayerNumInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBPlayerNumInfo.Merge(m, src)
}
func (m *DBPlayerNumInfo) XXX_Size() int {
	return xxx_messageInfo_DBPlayerNumInfo.Size(m)
}
func (m *DBPlayerNumInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DBPlayerNumInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DBPlayerNumInfo proto.InternalMessageInfo

func (m *DBPlayerNumInfo) GetDbid() int32 {
	if m != nil {
		return m.Dbid
	}
	return 0
}

func (m *DBPlayerNumInfo) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *DBPlayerNumInfo) GetMaxnum() int32 {
	if m != nil {
		return m.Maxnum
	}
	return 0
}

func (m *DBPlayerNumInfo) GetAccountTable() int32 {
	if m != nil {
		return m.AccountTable
	}
	return 0
}

type DBAccount struct {
	PlatformUid          string   `protobuf:"bytes,1,opt,name=platform_uid,json=platformUid,proto3" json:"platform_uid,omitempty"`
	GameUid              int32    `protobuf:"varint,2,opt,name=game_uid,json=gameUid,proto3" json:"game_uid,omitempty"`
	CreateTime           int32    `protobuf:"varint,3,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	Ip                   string   `protobuf:"bytes,4,opt,name=ip,proto3" json:"ip,omitempty"`
	Uidgroup             int32    `protobuf:"varint,5,opt,name=uidgroup,proto3" json:"uidgroup,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBAccount) Reset()         { *m = DBAccount{} }
func (m *DBAccount) String() string { return proto.CompactTextString(m) }
func (*DBAccount) ProtoMessage()    {}
func (*DBAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_88e703bb8c3f1871, []int{1}
}

func (m *DBAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBAccount.Unmarshal(m, b)
}
func (m *DBAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBAccount.Marshal(b, m, deterministic)
}
func (m *DBAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBAccount.Merge(m, src)
}
func (m *DBAccount) XXX_Size() int {
	return xxx_messageInfo_DBAccount.Size(m)
}
func (m *DBAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_DBAccount.DiscardUnknown(m)
}

var xxx_messageInfo_DBAccount proto.InternalMessageInfo

func (m *DBAccount) GetPlatformUid() string {
	if m != nil {
		return m.PlatformUid
	}
	return ""
}

func (m *DBAccount) GetGameUid() int32 {
	if m != nil {
		return m.GameUid
	}
	return 0
}

func (m *DBAccount) GetCreateTime() int32 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *DBAccount) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *DBAccount) GetUidgroup() int32 {
	if m != nil {
		return m.Uidgroup
	}
	return 0
}

type DBAccountLoad struct {
	Numinfo              []*DBPlayerNumInfo `protobuf:"bytes,1,rep,name=numinfo,proto3" json:"numinfo,omitempty"`
	Account              []*DBAccount       `protobuf:"bytes,2,rep,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *DBAccountLoad) Reset()         { *m = DBAccountLoad{} }
func (m *DBAccountLoad) String() string { return proto.CompactTextString(m) }
func (*DBAccountLoad) ProtoMessage()    {}
func (*DBAccountLoad) Descriptor() ([]byte, []int) {
	return fileDescriptor_88e703bb8c3f1871, []int{2}
}

func (m *DBAccountLoad) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBAccountLoad.Unmarshal(m, b)
}
func (m *DBAccountLoad) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBAccountLoad.Marshal(b, m, deterministic)
}
func (m *DBAccountLoad) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBAccountLoad.Merge(m, src)
}
func (m *DBAccountLoad) XXX_Size() int {
	return xxx_messageInfo_DBAccountLoad.Size(m)
}
func (m *DBAccountLoad) XXX_DiscardUnknown() {
	xxx_messageInfo_DBAccountLoad.DiscardUnknown(m)
}

var xxx_messageInfo_DBAccountLoad proto.InternalMessageInfo

func (m *DBAccountLoad) GetNuminfo() []*DBPlayerNumInfo {
	if m != nil {
		return m.Numinfo
	}
	return nil
}

func (m *DBAccountLoad) GetAccount() []*DBAccount {
	if m != nil {
		return m.Account
	}
	return nil
}

type DBAllRoleLevel struct {
	PlatformUid          string   `protobuf:"bytes,1,opt,name=platform_uid,json=platformUid,proto3" json:"platform_uid,omitempty"`
	Loginid              int32    `protobuf:"varint,2,opt,name=loginid,proto3" json:"loginid,omitempty"`
	Level                int32    `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	LogoutTime           int32    `protobuf:"varint,4,opt,name=logout_time,json=logoutTime,proto3" json:"logout_time,omitempty"`
	Cid                  int32    `protobuf:"varint,5,opt,name=cid,proto3" json:"cid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBAllRoleLevel) Reset()         { *m = DBAllRoleLevel{} }
func (m *DBAllRoleLevel) String() string { return proto.CompactTextString(m) }
func (*DBAllRoleLevel) ProtoMessage()    {}
func (*DBAllRoleLevel) Descriptor() ([]byte, []int) {
	return fileDescriptor_88e703bb8c3f1871, []int{3}
}

func (m *DBAllRoleLevel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBAllRoleLevel.Unmarshal(m, b)
}
func (m *DBAllRoleLevel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBAllRoleLevel.Marshal(b, m, deterministic)
}
func (m *DBAllRoleLevel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBAllRoleLevel.Merge(m, src)
}
func (m *DBAllRoleLevel) XXX_Size() int {
	return xxx_messageInfo_DBAllRoleLevel.Size(m)
}
func (m *DBAllRoleLevel) XXX_DiscardUnknown() {
	xxx_messageInfo_DBAllRoleLevel.DiscardUnknown(m)
}

var xxx_messageInfo_DBAllRoleLevel proto.InternalMessageInfo

func (m *DBAllRoleLevel) GetPlatformUid() string {
	if m != nil {
		return m.PlatformUid
	}
	return ""
}

func (m *DBAllRoleLevel) GetLoginid() int32 {
	if m != nil {
		return m.Loginid
	}
	return 0
}

func (m *DBAllRoleLevel) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *DBAllRoleLevel) GetLogoutTime() int32 {
	if m != nil {
		return m.LogoutTime
	}
	return 0
}

func (m *DBAllRoleLevel) GetCid() int32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

type DBBanUid struct {
	PlatformUid          string   `protobuf:"bytes,1,opt,name=platform_uid,json=platformUid,proto3" json:"platform_uid,omitempty"`
	Endtime              int32    `protobuf:"varint,2,opt,name=endtime,proto3" json:"endtime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBBanUid) Reset()         { *m = DBBanUid{} }
func (m *DBBanUid) String() string { return proto.CompactTextString(m) }
func (*DBBanUid) ProtoMessage()    {}
func (*DBBanUid) Descriptor() ([]byte, []int) {
	return fileDescriptor_88e703bb8c3f1871, []int{4}
}

func (m *DBBanUid) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBBanUid.Unmarshal(m, b)
}
func (m *DBBanUid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBBanUid.Marshal(b, m, deterministic)
}
func (m *DBBanUid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBBanUid.Merge(m, src)
}
func (m *DBBanUid) XXX_Size() int {
	return xxx_messageInfo_DBBanUid.Size(m)
}
func (m *DBBanUid) XXX_DiscardUnknown() {
	xxx_messageInfo_DBBanUid.DiscardUnknown(m)
}

var xxx_messageInfo_DBBanUid proto.InternalMessageInfo

func (m *DBBanUid) GetPlatformUid() string {
	if m != nil {
		return m.PlatformUid
	}
	return ""
}

func (m *DBBanUid) GetEndtime() int32 {
	if m != nil {
		return m.Endtime
	}
	return 0
}

type DBBanIp struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBBanIp) Reset()         { *m = DBBanIp{} }
func (m *DBBanIp) String() string { return proto.CompactTextString(m) }
func (*DBBanIp) ProtoMessage()    {}
func (*DBBanIp) Descriptor() ([]byte, []int) {
	return fileDescriptor_88e703bb8c3f1871, []int{5}
}

func (m *DBBanIp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBBanIp.Unmarshal(m, b)
}
func (m *DBBanIp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBBanIp.Marshal(b, m, deterministic)
}
func (m *DBBanIp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBBanIp.Merge(m, src)
}
func (m *DBBanIp) XXX_Size() int {
	return xxx_messageInfo_DBBanIp.Size(m)
}
func (m *DBBanIp) XXX_DiscardUnknown() {
	xxx_messageInfo_DBBanIp.DiscardUnknown(m)
}

var xxx_messageInfo_DBBanIp proto.InternalMessageInfo

func (m *DBBanIp) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type DBIpUnlimit struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Ipend                string   `protobuf:"bytes,2,opt,name=ipend,proto3" json:"ipend,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBIpUnlimit) Reset()         { *m = DBIpUnlimit{} }
func (m *DBIpUnlimit) String() string { return proto.CompactTextString(m) }
func (*DBIpUnlimit) ProtoMessage()    {}
func (*DBIpUnlimit) Descriptor() ([]byte, []int) {
	return fileDescriptor_88e703bb8c3f1871, []int{6}
}

func (m *DBIpUnlimit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBIpUnlimit.Unmarshal(m, b)
}
func (m *DBIpUnlimit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBIpUnlimit.Marshal(b, m, deterministic)
}
func (m *DBIpUnlimit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBIpUnlimit.Merge(m, src)
}
func (m *DBIpUnlimit) XXX_Size() int {
	return xxx_messageInfo_DBIpUnlimit.Size(m)
}
func (m *DBIpUnlimit) XXX_DiscardUnknown() {
	xxx_messageInfo_DBIpUnlimit.DiscardUnknown(m)
}

var xxx_messageInfo_DBIpUnlimit proto.InternalMessageInfo

func (m *DBIpUnlimit) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *DBIpUnlimit) GetIpend() string {
	if m != nil {
		return m.Ipend
	}
	return ""
}

type DBBanInfo struct {
	Banuid               []*DBBanUid    `protobuf:"bytes,1,rep,name=banuid,proto3" json:"banuid,omitempty"`
	Banip                []*DBBanIp     `protobuf:"bytes,2,rep,name=banip,proto3" json:"banip,omitempty"`
	Unlimitip            []*DBIpUnlimit `protobuf:"bytes,3,rep,name=unlimitip,proto3" json:"unlimitip,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DBBanInfo) Reset()         { *m = DBBanInfo{} }
func (m *DBBanInfo) String() string { return proto.CompactTextString(m) }
func (*DBBanInfo) ProtoMessage()    {}
func (*DBBanInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_88e703bb8c3f1871, []int{7}
}

func (m *DBBanInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBBanInfo.Unmarshal(m, b)
}
func (m *DBBanInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBBanInfo.Marshal(b, m, deterministic)
}
func (m *DBBanInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBBanInfo.Merge(m, src)
}
func (m *DBBanInfo) XXX_Size() int {
	return xxx_messageInfo_DBBanInfo.Size(m)
}
func (m *DBBanInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DBBanInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DBBanInfo proto.InternalMessageInfo

func (m *DBBanInfo) GetBanuid() []*DBBanUid {
	if m != nil {
		return m.Banuid
	}
	return nil
}

func (m *DBBanInfo) GetBanip() []*DBBanIp {
	if m != nil {
		return m.Banip
	}
	return nil
}

func (m *DBBanInfo) GetUnlimitip() []*DBIpUnlimit {
	if m != nil {
		return m.Unlimitip
	}
	return nil
}

type DBRoleList struct {
	Roles                []*DBPlayer `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	I32Ll                []int32     `protobuf:"varint,2,rep,packed,name=i32ll,proto3" json:"i32ll,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *DBRoleList) Reset()         { *m = DBRoleList{} }
func (m *DBRoleList) String() string { return proto.CompactTextString(m) }
func (*DBRoleList) ProtoMessage()    {}
func (*DBRoleList) Descriptor() ([]byte, []int) {
	return fileDescriptor_88e703bb8c3f1871, []int{8}
}

func (m *DBRoleList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBRoleList.Unmarshal(m, b)
}
func (m *DBRoleList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBRoleList.Marshal(b, m, deterministic)
}
func (m *DBRoleList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBRoleList.Merge(m, src)
}
func (m *DBRoleList) XXX_Size() int {
	return xxx_messageInfo_DBRoleList.Size(m)
}
func (m *DBRoleList) XXX_DiscardUnknown() {
	xxx_messageInfo_DBRoleList.DiscardUnknown(m)
}

var xxx_messageInfo_DBRoleList proto.InternalMessageInfo

func (m *DBRoleList) GetRoles() []*DBPlayer {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *DBRoleList) GetI32Ll() []int32 {
	if m != nil {
		return m.I32Ll
	}
	return nil
}

type DBPlayer struct {
	Cid                  int32    `protobuf:"varint,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Uid                  int32    `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Level                int32    `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	Gold                 int32    `protobuf:"varint,5,opt,name=gold,proto3" json:"gold,omitempty"`
	LoginTime            int32    `protobuf:"varint,6,opt,name=login_time,json=loginTime,proto3" json:"login_time,omitempty"`
	LogoutTime           int32    `protobuf:"varint,7,opt,name=logout_time,json=logoutTime,proto3" json:"logout_time,omitempty"`
	CreateTime           int32    `protobuf:"varint,8,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	Exp                  int32    `protobuf:"varint,9,opt,name=exp,proto3" json:"exp,omitempty"`
	PlatformUid          string   `protobuf:"bytes,10,opt,name=platform_uid,json=platformUid,proto3" json:"platform_uid,omitempty"`
	Signature            string   `protobuf:"bytes,11,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBPlayer) Reset()         { *m = DBPlayer{} }
func (m *DBPlayer) String() string { return proto.CompactTextString(m) }
func (*DBPlayer) ProtoMessage()    {}
func (*DBPlayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_88e703bb8c3f1871, []int{9}
}

func (m *DBPlayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBPlayer.Unmarshal(m, b)
}
func (m *DBPlayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBPlayer.Marshal(b, m, deterministic)
}
func (m *DBPlayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBPlayer.Merge(m, src)
}
func (m *DBPlayer) XXX_Size() int {
	return xxx_messageInfo_DBPlayer.Size(m)
}
func (m *DBPlayer) XXX_DiscardUnknown() {
	xxx_messageInfo_DBPlayer.DiscardUnknown(m)
}

var xxx_messageInfo_DBPlayer proto.InternalMessageInfo

func (m *DBPlayer) GetCid() int32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

func (m *DBPlayer) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *DBPlayer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DBPlayer) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *DBPlayer) GetGold() int32 {
	if m != nil {
		return m.Gold
	}
	return 0
}

func (m *DBPlayer) GetLoginTime() int32 {
	if m != nil {
		return m.LoginTime
	}
	return 0
}

func (m *DBPlayer) GetLogoutTime() int32 {
	if m != nil {
		return m.LogoutTime
	}
	return 0
}

func (m *DBPlayer) GetCreateTime() int32 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *DBPlayer) GetExp() int32 {
	if m != nil {
		return m.Exp
	}
	return 0
}

func (m *DBPlayer) GetPlatformUid() string {
	if m != nil {
		return m.PlatformUid
	}
	return ""
}

func (m *DBPlayer) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type DBChrItem struct {
	Cid                  int32    `protobuf:"varint,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Itemid               int32    `protobuf:"varint,2,opt,name=itemid,proto3" json:"itemid,omitempty"`
	Num                  int32    `protobuf:"varint,3,opt,name=num,proto3" json:"num,omitempty"`
	Isnew                int32    `protobuf:"varint,4,opt,name=isnew,proto3" json:"isnew,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBChrItem) Reset()         { *m = DBChrItem{} }
func (m *DBChrItem) String() string { return proto.CompactTextString(m) }
func (*DBChrItem) ProtoMessage()    {}
func (*DBChrItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_88e703bb8c3f1871, []int{10}
}

func (m *DBChrItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBChrItem.Unmarshal(m, b)
}
func (m *DBChrItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBChrItem.Marshal(b, m, deterministic)
}
func (m *DBChrItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBChrItem.Merge(m, src)
}
func (m *DBChrItem) XXX_Size() int {
	return xxx_messageInfo_DBChrItem.Size(m)
}
func (m *DBChrItem) XXX_DiscardUnknown() {
	xxx_messageInfo_DBChrItem.DiscardUnknown(m)
}

var xxx_messageInfo_DBChrItem proto.InternalMessageInfo

func (m *DBChrItem) GetCid() int32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

func (m *DBChrItem) GetItemid() int32 {
	if m != nil {
		return m.Itemid
	}
	return 0
}

func (m *DBChrItem) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *DBChrItem) GetIsnew() int32 {
	if m != nil {
		return m.Isnew
	}
	return 0
}

type DBChrRecord struct {
	Cid                  int32    `protobuf:"varint,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Type                 int32    `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Value                int32    `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBChrRecord) Reset()         { *m = DBChrRecord{} }
func (m *DBChrRecord) String() string { return proto.CompactTextString(m) }
func (*DBChrRecord) ProtoMessage()    {}
func (*DBChrRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_88e703bb8c3f1871, []int{11}
}

func (m *DBChrRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBChrRecord.Unmarshal(m, b)
}
func (m *DBChrRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBChrRecord.Marshal(b, m, deterministic)
}
func (m *DBChrRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBChrRecord.Merge(m, src)
}
func (m *DBChrRecord) XXX_Size() int {
	return xxx_messageInfo_DBChrRecord.Size(m)
}
func (m *DBChrRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_DBChrRecord.DiscardUnknown(m)
}

var xxx_messageInfo_DBChrRecord proto.InternalMessageInfo

func (m *DBChrRecord) GetCid() int32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

func (m *DBChrRecord) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *DBChrRecord) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type DBChrHero struct {
	Cid                  int32    `protobuf:"varint,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Heroid               int32    `protobuf:"varint,2,opt,name=heroid,proto3" json:"heroid,omitempty"`
	Level                int32    `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	Exp                  int32    `protobuf:"varint,4,opt,name=exp,proto3" json:"exp,omitempty"`
	Star                 int32    `protobuf:"varint,5,opt,name=star,proto3" json:"star,omitempty"`
	Skilllv1             int32    `protobuf:"varint,6,opt,name=skilllv1,proto3" json:"skilllv1,omitempty"`
	Skilllv2             int32    `protobuf:"varint,7,opt,name=skilllv2,proto3" json:"skilllv2,omitempty"`
	Skilllv3             int32    `protobuf:"varint,8,opt,name=skilllv3,proto3" json:"skilllv3,omitempty"`
	Skilllv4             int32    `protobuf:"varint,9,opt,name=skilllv4,proto3" json:"skilllv4,omitempty"`
	Order                int32    `protobuf:"varint,10,opt,name=order,proto3" json:"order,omitempty"`
	Talent               int32    `protobuf:"varint,11,opt,name=talent,proto3" json:"talent,omitempty"`
	Equip1               int64    `protobuf:"varint,15,opt,name=equip1,proto3" json:"equip1,omitempty"`
	Equip2               int64    `protobuf:"varint,16,opt,name=equip2,proto3" json:"equip2,omitempty"`
	Equip3               int64    `protobuf:"varint,17,opt,name=equip3,proto3" json:"equip3,omitempty"`
	Gem1                 int64    `protobuf:"varint,18,opt,name=gem1,proto3" json:"gem1,omitempty"`
	Gem2                 int64    `protobuf:"varint,19,opt,name=gem2,proto3" json:"gem2,omitempty"`
	Gem3                 int64    `protobuf:"varint,20,opt,name=gem3,proto3" json:"gem3,omitempty"`
	TalentSkill          string   `protobuf:"bytes,21,opt,name=talent_skill,json=talentSkill,proto3" json:"talent_skill,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBChrHero) Reset()         { *m = DBChrHero{} }
func (m *DBChrHero) String() string { return proto.CompactTextString(m) }
func (*DBChrHero) ProtoMessage()    {}
func (*DBChrHero) Descriptor() ([]byte, []int) {
	return fileDescriptor_88e703bb8c3f1871, []int{12}
}

func (m *DBChrHero) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBChrHero.Unmarshal(m, b)
}
func (m *DBChrHero) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBChrHero.Marshal(b, m, deterministic)
}
func (m *DBChrHero) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBChrHero.Merge(m, src)
}
func (m *DBChrHero) XXX_Size() int {
	return xxx_messageInfo_DBChrHero.Size(m)
}
func (m *DBChrHero) XXX_DiscardUnknown() {
	xxx_messageInfo_DBChrHero.DiscardUnknown(m)
}

var xxx_messageInfo_DBChrHero proto.InternalMessageInfo

func (m *DBChrHero) GetCid() int32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

func (m *DBChrHero) GetHeroid() int32 {
	if m != nil {
		return m.Heroid
	}
	return 0
}

func (m *DBChrHero) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *DBChrHero) GetExp() int32 {
	if m != nil {
		return m.Exp
	}
	return 0
}

func (m *DBChrHero) GetStar() int32 {
	if m != nil {
		return m.Star
	}
	return 0
}

func (m *DBChrHero) GetSkilllv1() int32 {
	if m != nil {
		return m.Skilllv1
	}
	return 0
}

func (m *DBChrHero) GetSkilllv2() int32 {
	if m != nil {
		return m.Skilllv2
	}
	return 0
}

func (m *DBChrHero) GetSkilllv3() int32 {
	if m != nil {
		return m.Skilllv3
	}
	return 0
}

func (m *DBChrHero) GetSkilllv4() int32 {
	if m != nil {
		return m.Skilllv4
	}
	return 0
}

func (m *DBChrHero) GetOrder() int32 {
	if m != nil {
		return m.Order
	}
	return 0
}

func (m *DBChrHero) GetTalent() int32 {
	if m != nil {
		return m.Talent
	}
	return 0
}

func (m *DBChrHero) GetEquip1() int64 {
	if m != nil {
		return m.Equip1
	}
	return 0
}

func (m *DBChrHero) GetEquip2() int64 {
	if m != nil {
		return m.Equip2
	}
	return 0
}

func (m *DBChrHero) GetEquip3() int64 {
	if m != nil {
		return m.Equip3
	}
	return 0
}

func (m *DBChrHero) GetGem1() int64 {
	if m != nil {
		return m.Gem1
	}
	return 0
}

func (m *DBChrHero) GetGem2() int64 {
	if m != nil {
		return m.Gem2
	}
	return 0
}

func (m *DBChrHero) GetGem3() int64 {
	if m != nil {
		return m.Gem3
	}
	return 0
}

func (m *DBChrHero) GetTalentSkill() string {
	if m != nil {
		return m.TalentSkill
	}
	return ""
}

type DBChrDungeon struct {
	Cid                  int32    `protobuf:"varint,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Id                   int32    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Star                 int32    `protobuf:"varint,3,opt,name=star,proto3" json:"star,omitempty"`
	FirstReward          int32    `protobuf:"varint,4,opt,name=first_reward,json=firstReward,proto3" json:"first_reward,omitempty"`
	Mopup                int32    `protobuf:"varint,5,opt,name=mopup,proto3" json:"mopup,omitempty"`
	MopupTime            int32    `protobuf:"varint,6,opt,name=mopup_time,json=mopupTime,proto3" json:"mopup_time,omitempty"`
	Achieve              int32    `protobuf:"varint,7,opt,name=achieve,proto3" json:"achieve,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBChrDungeon) Reset()         { *m = DBChrDungeon{} }
func (m *DBChrDungeon) String() string { return proto.CompactTextString(m) }
func (*DBChrDungeon) ProtoMessage()    {}
func (*DBChrDungeon) Descriptor() ([]byte, []int) {
	return fileDescriptor_88e703bb8c3f1871, []int{13}
}

func (m *DBChrDungeon) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBChrDungeon.Unmarshal(m, b)
}
func (m *DBChrDungeon) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBChrDungeon.Marshal(b, m, deterministic)
}
func (m *DBChrDungeon) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBChrDungeon.Merge(m, src)
}
func (m *DBChrDungeon) XXX_Size() int {
	return xxx_messageInfo_DBChrDungeon.Size(m)
}
func (m *DBChrDungeon) XXX_DiscardUnknown() {
	xxx_messageInfo_DBChrDungeon.DiscardUnknown(m)
}

var xxx_messageInfo_DBChrDungeon proto.InternalMessageInfo

func (m *DBChrDungeon) GetCid() int32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

func (m *DBChrDungeon) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DBChrDungeon) GetStar() int32 {
	if m != nil {
		return m.Star
	}
	return 0
}

func (m *DBChrDungeon) GetFirstReward() int32 {
	if m != nil {
		return m.FirstReward
	}
	return 0
}

func (m *DBChrDungeon) GetMopup() int32 {
	if m != nil {
		return m.Mopup
	}
	return 0
}

func (m *DBChrDungeon) GetMopupTime() int32 {
	if m != nil {
		return m.MopupTime
	}
	return 0
}

func (m *DBChrDungeon) GetAchieve() int32 {
	if m != nil {
		return m.Achieve
	}
	return 0
}

type DBChrShopLimit struct {
	Cid                  int32    `protobuf:"varint,1,opt,name=cid,proto3" json:"cid,omitempty"`
	ShopId               int32    `protobuf:"varint,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	Count                int32    `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	LimitType            int32    `protobuf:"varint,4,opt,name=limit_type,json=limitType,proto3" json:"limit_type,omitempty"`
	Time                 int32    `protobuf:"varint,5,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBChrShopLimit) Reset()         { *m = DBChrShopLimit{} }
func (m *DBChrShopLimit) String() string { return proto.CompactTextString(m) }
func (*DBChrShopLimit) ProtoMessage()    {}
func (*DBChrShopLimit) Descriptor() ([]byte, []int) {
	return fileDescriptor_88e703bb8c3f1871, []int{14}
}

func (m *DBChrShopLimit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBChrShopLimit.Unmarshal(m, b)
}
func (m *DBChrShopLimit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBChrShopLimit.Marshal(b, m, deterministic)
}
func (m *DBChrShopLimit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBChrShopLimit.Merge(m, src)
}
func (m *DBChrShopLimit) XXX_Size() int {
	return xxx_messageInfo_DBChrShopLimit.Size(m)
}
func (m *DBChrShopLimit) XXX_DiscardUnknown() {
	xxx_messageInfo_DBChrShopLimit.DiscardUnknown(m)
}

var xxx_messageInfo_DBChrShopLimit proto.InternalMessageInfo

func (m *DBChrShopLimit) GetCid() int32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

func (m *DBChrShopLimit) GetShopId() int32 {
	if m != nil {
		return m.ShopId
	}
	return 0
}

func (m *DBChrShopLimit) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *DBChrShopLimit) GetLimitType() int32 {
	if m != nil {
		return m.LimitType
	}
	return 0
}

func (m *DBChrShopLimit) GetTime() int32 {
	if m != nil {
		return m.Time
	}
	return 0
}

type DBChrBattleData struct {
	Cid                  int32    `protobuf:"varint,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Index                int32    `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Time                 int32    `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
	Compress             int32    `protobuf:"varint,4,opt,name=compress,proto3" json:"compress,omitempty"`
	Orglen               int32    `protobuf:"varint,5,opt,name=orglen,proto3" json:"orglen,omitempty"`
	Data                 []byte   `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	Md5                  string   `protobuf:"bytes,7,opt,name=md5,proto3" json:"md5,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBChrBattleData) Reset()         { *m = DBChrBattleData{} }
func (m *DBChrBattleData) String() string { return proto.CompactTextString(m) }
func (*DBChrBattleData) ProtoMessage()    {}
func (*DBChrBattleData) Descriptor() ([]byte, []int) {
	return fileDescriptor_88e703bb8c3f1871, []int{15}
}

func (m *DBChrBattleData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBChrBattleData.Unmarshal(m, b)
}
func (m *DBChrBattleData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBChrBattleData.Marshal(b, m, deterministic)
}
func (m *DBChrBattleData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBChrBattleData.Merge(m, src)
}
func (m *DBChrBattleData) XXX_Size() int {
	return xxx_messageInfo_DBChrBattleData.Size(m)
}
func (m *DBChrBattleData) XXX_DiscardUnknown() {
	xxx_messageInfo_DBChrBattleData.DiscardUnknown(m)
}

var xxx_messageInfo_DBChrBattleData proto.InternalMessageInfo

func (m *DBChrBattleData) GetCid() int32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

func (m *DBChrBattleData) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *DBChrBattleData) GetTime() int32 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *DBChrBattleData) GetCompress() int32 {
	if m != nil {
		return m.Compress
	}
	return 0
}

func (m *DBChrBattleData) GetOrglen() int32 {
	if m != nil {
		return m.Orglen
	}
	return 0
}

func (m *DBChrBattleData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *DBChrBattleData) GetMd5() string {
	if m != nil {
		return m.Md5
	}
	return ""
}

type DBChrTask struct {
	Cid                  int32    `protobuf:"varint,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Id                   int32    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Value                int32    `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	State                int32    `protobuf:"varint,4,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBChrTask) Reset()         { *m = DBChrTask{} }
func (m *DBChrTask) String() string { return proto.CompactTextString(m) }
func (*DBChrTask) ProtoMessage()    {}
func (*DBChrTask) Descriptor() ([]byte, []int) {
	return fileDescriptor_88e703bb8c3f1871, []int{16}
}

func (m *DBChrTask) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBChrTask.Unmarshal(m, b)
}
func (m *DBChrTask) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBChrTask.Marshal(b, m, deterministic)
}
func (m *DBChrTask) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBChrTask.Merge(m, src)
}
func (m *DBChrTask) XXX_Size() int {
	return xxx_messageInfo_DBChrTask.Size(m)
}
func (m *DBChrTask) XXX_DiscardUnknown() {
	xxx_messageInfo_DBChrTask.DiscardUnknown(m)
}

var xxx_messageInfo_DBChrTask proto.InternalMessageInfo

func (m *DBChrTask) GetCid() int32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

func (m *DBChrTask) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DBChrTask) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *DBChrTask) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

type DBChrAchievement struct {
	Cid                  int32    `protobuf:"varint,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Id                   int32    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Value                int32    `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	State                int32    `protobuf:"varint,4,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBChrAchievement) Reset()         { *m = DBChrAchievement{} }
func (m *DBChrAchievement) String() string { return proto.CompactTextString(m) }
func (*DBChrAchievement) ProtoMessage()    {}
func (*DBChrAchievement) Descriptor() ([]byte, []int) {
	return fileDescriptor_88e703bb8c3f1871, []int{17}
}

func (m *DBChrAchievement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBChrAchievement.Unmarshal(m, b)
}
func (m *DBChrAchievement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBChrAchievement.Marshal(b, m, deterministic)
}
func (m *DBChrAchievement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBChrAchievement.Merge(m, src)
}
func (m *DBChrAchievement) XXX_Size() int {
	return xxx_messageInfo_DBChrAchievement.Size(m)
}
func (m *DBChrAchievement) XXX_DiscardUnknown() {
	xxx_messageInfo_DBChrAchievement.DiscardUnknown(m)
}

var xxx_messageInfo_DBChrAchievement proto.InternalMessageInfo

func (m *DBChrAchievement) GetCid() int32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

func (m *DBChrAchievement) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DBChrAchievement) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *DBChrAchievement) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

type DBChrMail struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Cid                  int32    `protobuf:"varint,2,opt,name=cid,proto3" json:"cid,omitempty"`
	Sender               string   `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	Title                string   `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Content              string   `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Reward               string   `protobuf:"bytes,6,opt,name=reward,proto3" json:"reward,omitempty"`
	State                int32    `protobuf:"varint,7,opt,name=state,proto3" json:"state,omitempty"`
	Reason               int32    `protobuf:"varint,8,opt,name=reason,proto3" json:"reason,omitempty"`
	Time                 int32    `protobuf:"varint,9,opt,name=time,proto3" json:"time,omitempty"`
	Mailid               int32    `protobuf:"varint,10,opt,name=mailid,proto3" json:"mailid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBChrMail) Reset()         { *m = DBChrMail{} }
func (m *DBChrMail) String() string { return proto.CompactTextString(m) }
func (*DBChrMail) ProtoMessage()    {}
func (*DBChrMail) Descriptor() ([]byte, []int) {
	return fileDescriptor_88e703bb8c3f1871, []int{18}
}

func (m *DBChrMail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBChrMail.Unmarshal(m, b)
}
func (m *DBChrMail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBChrMail.Marshal(b, m, deterministic)
}
func (m *DBChrMail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBChrMail.Merge(m, src)
}
func (m *DBChrMail) XXX_Size() int {
	return xxx_messageInfo_DBChrMail.Size(m)
}
func (m *DBChrMail) XXX_DiscardUnknown() {
	xxx_messageInfo_DBChrMail.DiscardUnknown(m)
}

var xxx_messageInfo_DBChrMail proto.InternalMessageInfo

func (m *DBChrMail) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DBChrMail) GetCid() int32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

func (m *DBChrMail) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *DBChrMail) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *DBChrMail) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *DBChrMail) GetReward() string {
	if m != nil {
		return m.Reward
	}
	return ""
}

func (m *DBChrMail) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *DBChrMail) GetReason() int32 {
	if m != nil {
		return m.Reason
	}
	return 0
}

func (m *DBChrMail) GetTime() int32 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *DBChrMail) GetMailid() int32 {
	if m != nil {
		return m.Mailid
	}
	return 0
}

type DBChrServerMail struct {
	Cid                  int32    `protobuf:"varint,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Id                   int32    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Time                 int32    `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBChrServerMail) Reset()         { *m = DBChrServerMail{} }
func (m *DBChrServerMail) String() string { return proto.CompactTextString(m) }
func (*DBChrServerMail) ProtoMessage()    {}
func (*DBChrServerMail) Descriptor() ([]byte, []int) {
	return fileDescriptor_88e703bb8c3f1871, []int{19}
}

func (m *DBChrServerMail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBChrServerMail.Unmarshal(m, b)
}
func (m *DBChrServerMail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBChrServerMail.Marshal(b, m, deterministic)
}
func (m *DBChrServerMail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBChrServerMail.Merge(m, src)
}
func (m *DBChrServerMail) XXX_Size() int {
	return xxx_messageInfo_DBChrServerMail.Size(m)
}
func (m *DBChrServerMail) XXX_DiscardUnknown() {
	xxx_messageInfo_DBChrServerMail.DiscardUnknown(m)
}

var xxx_messageInfo_DBChrServerMail proto.InternalMessageInfo

func (m *DBChrServerMail) GetCid() int32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

func (m *DBChrServerMail) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DBChrServerMail) GetTime() int32 {
	if m != nil {
		return m.Time
	}
	return 0
}

type DBChrHeroTeam struct {
	Cid                  int32    `protobuf:"varint,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Index                int32    `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Id1                  int32    `protobuf:"varint,3,opt,name=id1,proto3" json:"id1,omitempty"`
	Id2                  int32    `protobuf:"varint,4,opt,name=id2,proto3" json:"id2,omitempty"`
	Id3                  int32    `protobuf:"varint,5,opt,name=id3,proto3" json:"id3,omitempty"`
	Id4                  int32    `protobuf:"varint,6,opt,name=id4,proto3" json:"id4,omitempty"`
	Id5                  int32    `protobuf:"varint,7,opt,name=id5,proto3" json:"id5,omitempty"`
	Id6                  int32    `protobuf:"varint,8,opt,name=id6,proto3" json:"id6,omitempty"`
	Name                 string   `protobuf:"bytes,9,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBChrHeroTeam) Reset()         { *m = DBChrHeroTeam{} }
func (m *DBChrHeroTeam) String() string { return proto.CompactTextString(m) }
func (*DBChrHeroTeam) ProtoMessage()    {}
func (*DBChrHeroTeam) Descriptor() ([]byte, []int) {
	return fileDescriptor_88e703bb8c3f1871, []int{20}
}

func (m *DBChrHeroTeam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBChrHeroTeam.Unmarshal(m, b)
}
func (m *DBChrHeroTeam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBChrHeroTeam.Marshal(b, m, deterministic)
}
func (m *DBChrHeroTeam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBChrHeroTeam.Merge(m, src)
}
func (m *DBChrHeroTeam) XXX_Size() int {
	return xxx_messageInfo_DBChrHeroTeam.Size(m)
}
func (m *DBChrHeroTeam) XXX_DiscardUnknown() {
	xxx_messageInfo_DBChrHeroTeam.DiscardUnknown(m)
}

var xxx_messageInfo_DBChrHeroTeam proto.InternalMessageInfo

func (m *DBChrHeroTeam) GetCid() int32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

func (m *DBChrHeroTeam) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *DBChrHeroTeam) GetId1() int32 {
	if m != nil {
		return m.Id1
	}
	return 0
}

func (m *DBChrHeroTeam) GetId2() int32 {
	if m != nil {
		return m.Id2
	}
	return 0
}

func (m *DBChrHeroTeam) GetId3() int32 {
	if m != nil {
		return m.Id3
	}
	return 0
}

func (m *DBChrHeroTeam) GetId4() int32 {
	if m != nil {
		return m.Id4
	}
	return 0
}

func (m *DBChrHeroTeam) GetId5() int32 {
	if m != nil {
		return m.Id5
	}
	return 0
}

func (m *DBChrHeroTeam) GetId6() int32 {
	if m != nil {
		return m.Id6
	}
	return 0
}

func (m *DBChrHeroTeam) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DBChrClientRecord struct {
	Cid                  int32    `protobuf:"varint,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Id                   int32    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Value                int32    `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBChrClientRecord) Reset()         { *m = DBChrClientRecord{} }
func (m *DBChrClientRecord) String() string { return proto.CompactTextString(m) }
func (*DBChrClientRecord) ProtoMessage()    {}
func (*DBChrClientRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_88e703bb8c3f1871, []int{21}
}

func (m *DBChrClientRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBChrClientRecord.Unmarshal(m, b)
}
func (m *DBChrClientRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBChrClientRecord.Marshal(b, m, deterministic)
}
func (m *DBChrClientRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBChrClientRecord.Merge(m, src)
}
func (m *DBChrClientRecord) XXX_Size() int {
	return xxx_messageInfo_DBChrClientRecord.Size(m)
}
func (m *DBChrClientRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_DBChrClientRecord.DiscardUnknown(m)
}

var xxx_messageInfo_DBChrClientRecord proto.InternalMessageInfo

func (m *DBChrClientRecord) GetCid() int32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

func (m *DBChrClientRecord) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DBChrClientRecord) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type DBChrRelation struct {
	Cid                  int32    `protobuf:"varint,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Tocid                int32    `protobuf:"varint,2,opt,name=tocid,proto3" json:"tocid,omitempty"`
	Type                 int32    `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	Time                 int32    `protobuf:"varint,4,opt,name=time,proto3" json:"time,omitempty"`
	Rewardget            int32    `protobuf:"varint,5,opt,name=rewardget,proto3" json:"rewardget,omitempty"`
	Rewardsend           int32    `protobuf:"varint,6,opt,name=rewardsend,proto3" json:"rewardsend,omitempty"`
	Name                 string   `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	LogoutTime           int32    `protobuf:"varint,8,opt,name=logout_time,json=logoutTime,proto3" json:"logout_time,omitempty"`
	Notes                string   `protobuf:"bytes,9,opt,name=notes,proto3" json:"notes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBChrRelation) Reset()         { *m = DBChrRelation{} }
func (m *DBChrRelation) String() string { return proto.CompactTextString(m) }
func (*DBChrRelation) ProtoMessage()    {}
func (*DBChrRelation) Descriptor() ([]byte, []int) {
	return fileDescriptor_88e703bb8c3f1871, []int{22}
}

func (m *DBChrRelation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBChrRelation.Unmarshal(m, b)
}
func (m *DBChrRelation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBChrRelation.Marshal(b, m, deterministic)
}
func (m *DBChrRelation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBChrRelation.Merge(m, src)
}
func (m *DBChrRelation) XXX_Size() int {
	return xxx_messageInfo_DBChrRelation.Size(m)
}
func (m *DBChrRelation) XXX_DiscardUnknown() {
	xxx_messageInfo_DBChrRelation.DiscardUnknown(m)
}

var xxx_messageInfo_DBChrRelation proto.InternalMessageInfo

func (m *DBChrRelation) GetCid() int32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

func (m *DBChrRelation) GetTocid() int32 {
	if m != nil {
		return m.Tocid
	}
	return 0
}

func (m *DBChrRelation) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *DBChrRelation) GetTime() int32 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *DBChrRelation) GetRewardget() int32 {
	if m != nil {
		return m.Rewardget
	}
	return 0
}

func (m *DBChrRelation) GetRewardsend() int32 {
	if m != nil {
		return m.Rewardsend
	}
	return 0
}

func (m *DBChrRelation) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DBChrRelation) GetLogoutTime() int32 {
	if m != nil {
		return m.LogoutTime
	}
	return 0
}

func (m *DBChrRelation) GetNotes() string {
	if m != nil {
		return m.Notes
	}
	return ""
}

type DBRelationList struct {
	Data                 []*DBChrRelation `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *DBRelationList) Reset()         { *m = DBRelationList{} }
func (m *DBRelationList) String() string { return proto.CompactTextString(m) }
func (*DBRelationList) ProtoMessage()    {}
func (*DBRelationList) Descriptor() ([]byte, []int) {
	return fileDescriptor_88e703bb8c3f1871, []int{23}
}

func (m *DBRelationList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBRelationList.Unmarshal(m, b)
}
func (m *DBRelationList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBRelationList.Marshal(b, m, deterministic)
}
func (m *DBRelationList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBRelationList.Merge(m, src)
}
func (m *DBRelationList) XXX_Size() int {
	return xxx_messageInfo_DBRelationList.Size(m)
}
func (m *DBRelationList) XXX_DiscardUnknown() {
	xxx_messageInfo_DBRelationList.DiscardUnknown(m)
}

var xxx_messageInfo_DBRelationList proto.InternalMessageInfo

func (m *DBRelationList) GetData() []*DBChrRelation {
	if m != nil {
		return m.Data
	}
	return nil
}

type DBPlayerAllData struct {
	Player               *DBPlayer            `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	Item                 []*DBChrItem         `protobuf:"bytes,2,rep,name=item,proto3" json:"item,omitempty"`
	Record               []*DBChrRecord       `protobuf:"bytes,3,rep,name=record,proto3" json:"record,omitempty"`
	Hero                 []*DBChrHero         `protobuf:"bytes,4,rep,name=hero,proto3" json:"hero,omitempty"`
	Dungeon              []*DBChrDungeon      `protobuf:"bytes,5,rep,name=dungeon,proto3" json:"dungeon,omitempty"`
	ShopLimit            []*DBChrShopLimit    `protobuf:"bytes,6,rep,name=shop_limit,json=shopLimit,proto3" json:"shop_limit,omitempty"`
	Task                 []*DBChrTask         `protobuf:"bytes,7,rep,name=task,proto3" json:"task,omitempty"`
	Achievement          []*DBChrAchievement  `protobuf:"bytes,8,rep,name=achievement,proto3" json:"achievement,omitempty"`
	Mail                 []*DBChrMail         `protobuf:"bytes,9,rep,name=mail,proto3" json:"mail,omitempty"`
	ServerMail           []*DBChrServerMail   `protobuf:"bytes,10,rep,name=server_mail,json=serverMail,proto3" json:"server_mail,omitempty"`
	Equip                []*MemEquip          `protobuf:"bytes,11,rep,name=equip,proto3" json:"equip,omitempty"`
	Gem                  []*MemGem            `protobuf:"bytes,12,rep,name=gem,proto3" json:"gem,omitempty"`
	HeroTeam             []*DBChrHeroTeam     `protobuf:"bytes,13,rep,name=hero_team,json=heroTeam,proto3" json:"hero_team,omitempty"`
	ClientRecord         []*DBChrClientRecord `protobuf:"bytes,14,rep,name=client_record,json=clientRecord,proto3" json:"client_record,omitempty"`
	Relation             []*DBChrRelation     `protobuf:"bytes,15,rep,name=relation,proto3" json:"relation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DBPlayerAllData) Reset()         { *m = DBPlayerAllData{} }
func (m *DBPlayerAllData) String() string { return proto.CompactTextString(m) }
func (*DBPlayerAllData) ProtoMessage()    {}
func (*DBPlayerAllData) Descriptor() ([]byte, []int) {
	return fileDescriptor_88e703bb8c3f1871, []int{24}
}

func (m *DBPlayerAllData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBPlayerAllData.Unmarshal(m, b)
}
func (m *DBPlayerAllData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBPlayerAllData.Marshal(b, m, deterministic)
}
func (m *DBPlayerAllData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBPlayerAllData.Merge(m, src)
}
func (m *DBPlayerAllData) XXX_Size() int {
	return xxx_messageInfo_DBPlayerAllData.Size(m)
}
func (m *DBPlayerAllData) XXX_DiscardUnknown() {
	xxx_messageInfo_DBPlayerAllData.DiscardUnknown(m)
}

var xxx_messageInfo_DBPlayerAllData proto.InternalMessageInfo

func (m *DBPlayerAllData) GetPlayer() *DBPlayer {
	if m != nil {
		return m.Player
	}
	return nil
}

func (m *DBPlayerAllData) GetItem() []*DBChrItem {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *DBPlayerAllData) GetRecord() []*DBChrRecord {
	if m != nil {
		return m.Record
	}
	return nil
}

func (m *DBPlayerAllData) GetHero() []*DBChrHero {
	if m != nil {
		return m.Hero
	}
	return nil
}

func (m *DBPlayerAllData) GetDungeon() []*DBChrDungeon {
	if m != nil {
		return m.Dungeon
	}
	return nil
}

func (m *DBPlayerAllData) GetShopLimit() []*DBChrShopLimit {
	if m != nil {
		return m.ShopLimit
	}
	return nil
}

func (m *DBPlayerAllData) GetTask() []*DBChrTask {
	if m != nil {
		return m.Task
	}
	return nil
}

func (m *DBPlayerAllData) GetAchievement() []*DBChrAchievement {
	if m != nil {
		return m.Achievement
	}
	return nil
}

func (m *DBPlayerAllData) GetMail() []*DBChrMail {
	if m != nil {
		return m.Mail
	}
	return nil
}

func (m *DBPlayerAllData) GetServerMail() []*DBChrServerMail {
	if m != nil {
		return m.ServerMail
	}
	return nil
}

func (m *DBPlayerAllData) GetEquip() []*MemEquip {
	if m != nil {
		return m.Equip
	}
	return nil
}

func (m *DBPlayerAllData) GetGem() []*MemGem {
	if m != nil {
		return m.Gem
	}
	return nil
}

func (m *DBPlayerAllData) GetHeroTeam() []*DBChrHeroTeam {
	if m != nil {
		return m.HeroTeam
	}
	return nil
}

func (m *DBPlayerAllData) GetClientRecord() []*DBChrClientRecord {
	if m != nil {
		return m.ClientRecord
	}
	return nil
}

func (m *DBPlayerAllData) GetRelation() []*DBChrRelation {
	if m != nil {
		return m.Relation
	}
	return nil
}

type DBServerMail struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Sender               string   `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Reward               string   `protobuf:"bytes,5,opt,name=reward,proto3" json:"reward,omitempty"`
	Time                 int32    `protobuf:"varint,6,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBServerMail) Reset()         { *m = DBServerMail{} }
func (m *DBServerMail) String() string { return proto.CompactTextString(m) }
func (*DBServerMail) ProtoMessage()    {}
func (*DBServerMail) Descriptor() ([]byte, []int) {
	return fileDescriptor_88e703bb8c3f1871, []int{25}
}

func (m *DBServerMail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBServerMail.Unmarshal(m, b)
}
func (m *DBServerMail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBServerMail.Marshal(b, m, deterministic)
}
func (m *DBServerMail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBServerMail.Merge(m, src)
}
func (m *DBServerMail) XXX_Size() int {
	return xxx_messageInfo_DBServerMail.Size(m)
}
func (m *DBServerMail) XXX_DiscardUnknown() {
	xxx_messageInfo_DBServerMail.DiscardUnknown(m)
}

var xxx_messageInfo_DBServerMail proto.InternalMessageInfo

func (m *DBServerMail) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DBServerMail) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *DBServerMail) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *DBServerMail) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *DBServerMail) GetReward() string {
	if m != nil {
		return m.Reward
	}
	return ""
}

func (m *DBServerMail) GetTime() int32 {
	if m != nil {
		return m.Time
	}
	return 0
}

type MailList struct {
	Data                 []*DBServerMail `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *MailList) Reset()         { *m = MailList{} }
func (m *MailList) String() string { return proto.CompactTextString(m) }
func (*MailList) ProtoMessage()    {}
func (*MailList) Descriptor() ([]byte, []int) {
	return fileDescriptor_88e703bb8c3f1871, []int{26}
}

func (m *MailList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailList.Unmarshal(m, b)
}
func (m *MailList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailList.Marshal(b, m, deterministic)
}
func (m *MailList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailList.Merge(m, src)
}
func (m *MailList) XXX_Size() int {
	return xxx_messageInfo_MailList.Size(m)
}
func (m *MailList) XXX_DiscardUnknown() {
	xxx_messageInfo_MailList.DiscardUnknown(m)
}

var xxx_messageInfo_MailList proto.InternalMessageInfo

func (m *MailList) GetData() []*DBServerMail {
	if m != nil {
		return m.Data
	}
	return nil
}

type DBSqlData struct {
	Table                int32    `protobuf:"varint,1,opt,name=table,proto3" json:"table,omitempty"`
	Opt                  int32    `protobuf:"varint,2,opt,name=opt,proto3" json:"opt,omitempty"`
	Keys                 []string `protobuf:"bytes,3,rep,name=keys,proto3" json:"keys,omitempty"`
	Data                 []byte   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBSqlData) Reset()         { *m = DBSqlData{} }
func (m *DBSqlData) String() string { return proto.CompactTextString(m) }
func (*DBSqlData) ProtoMessage()    {}
func (*DBSqlData) Descriptor() ([]byte, []int) {
	return fileDescriptor_88e703bb8c3f1871, []int{27}
}

func (m *DBSqlData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBSqlData.Unmarshal(m, b)
}
func (m *DBSqlData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBSqlData.Marshal(b, m, deterministic)
}
func (m *DBSqlData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBSqlData.Merge(m, src)
}
func (m *DBSqlData) XXX_Size() int {
	return xxx_messageInfo_DBSqlData.Size(m)
}
func (m *DBSqlData) XXX_DiscardUnknown() {
	xxx_messageInfo_DBSqlData.DiscardUnknown(m)
}

var xxx_messageInfo_DBSqlData proto.InternalMessageInfo

func (m *DBSqlData) GetTable() int32 {
	if m != nil {
		return m.Table
	}
	return 0
}

func (m *DBSqlData) GetOpt() int32 {
	if m != nil {
		return m.Opt
	}
	return 0
}

func (m *DBSqlData) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *DBSqlData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type DBSqlDataList struct {
	Cid                  int32        `protobuf:"varint,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Datas                []*DBSqlData `protobuf:"bytes,2,rep,name=datas,proto3" json:"datas,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *DBSqlDataList) Reset()         { *m = DBSqlDataList{} }
func (m *DBSqlDataList) String() string { return proto.CompactTextString(m) }
func (*DBSqlDataList) ProtoMessage()    {}
func (*DBSqlDataList) Descriptor() ([]byte, []int) {
	return fileDescriptor_88e703bb8c3f1871, []int{28}
}

func (m *DBSqlDataList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBSqlDataList.Unmarshal(m, b)
}
func (m *DBSqlDataList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBSqlDataList.Marshal(b, m, deterministic)
}
func (m *DBSqlDataList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBSqlDataList.Merge(m, src)
}
func (m *DBSqlDataList) XXX_Size() int {
	return xxx_messageInfo_DBSqlDataList.Size(m)
}
func (m *DBSqlDataList) XXX_DiscardUnknown() {
	xxx_messageInfo_DBSqlDataList.DiscardUnknown(m)
}

var xxx_messageInfo_DBSqlDataList proto.InternalMessageInfo

func (m *DBSqlDataList) GetCid() int32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

func (m *DBSqlDataList) GetDatas() []*DBSqlData {
	if m != nil {
		return m.Datas
	}
	return nil
}

type DbPlayerMsg struct {
	Cid                  int32    `protobuf:"varint,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DbPlayerMsg) Reset()         { *m = DbPlayerMsg{} }
func (m *DbPlayerMsg) String() string { return proto.CompactTextString(m) }
func (*DbPlayerMsg) ProtoMessage()    {}
func (*DbPlayerMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_88e703bb8c3f1871, []int{29}
}

func (m *DbPlayerMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DbPlayerMsg.Unmarshal(m, b)
}
func (m *DbPlayerMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DbPlayerMsg.Marshal(b, m, deterministic)
}
func (m *DbPlayerMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DbPlayerMsg.Merge(m, src)
}
func (m *DbPlayerMsg) XXX_Size() int {
	return xxx_messageInfo_DbPlayerMsg.Size(m)
}
func (m *DbPlayerMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_DbPlayerMsg.DiscardUnknown(m)
}

var xxx_messageInfo_DbPlayerMsg proto.InternalMessageInfo

func (m *DbPlayerMsg) GetCid() int32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

func (m *DbPlayerMsg) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type LogUseitem struct {
	Cid                  int32    `protobuf:"varint,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Itemid               int32    `protobuf:"varint,2,opt,name=itemid,proto3" json:"itemid,omitempty"`
	Type                 int32    `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	Num                  int32    `protobuf:"varint,4,opt,name=num,proto3" json:"num,omitempty"`
	Reason               int32    `protobuf:"varint,5,opt,name=reason,proto3" json:"reason,omitempty"`
	Realid               int64    `protobuf:"varint,6,opt,name=realid,proto3" json:"realid,omitempty"`
	Time                 int32    `protobuf:"varint,7,opt,name=time,proto3" json:"time,omitempty"`
	Change               int32    `protobuf:"varint,8,opt,name=change,proto3" json:"change,omitempty"`
	Param                int32    `protobuf:"varint,9,opt,name=param,proto3" json:"param,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogUseitem) Reset()         { *m = LogUseitem{} }
func (m *LogUseitem) String() string { return proto.CompactTextString(m) }
func (*LogUseitem) ProtoMessage()    {}
func (*LogUseitem) Descriptor() ([]byte, []int) {
	return fileDescriptor_88e703bb8c3f1871, []int{30}
}

func (m *LogUseitem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogUseitem.Unmarshal(m, b)
}
func (m *LogUseitem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogUseitem.Marshal(b, m, deterministic)
}
func (m *LogUseitem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogUseitem.Merge(m, src)
}
func (m *LogUseitem) XXX_Size() int {
	return xxx_messageInfo_LogUseitem.Size(m)
}
func (m *LogUseitem) XXX_DiscardUnknown() {
	xxx_messageInfo_LogUseitem.DiscardUnknown(m)
}

var xxx_messageInfo_LogUseitem proto.InternalMessageInfo

func (m *LogUseitem) GetCid() int32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

func (m *LogUseitem) GetItemid() int32 {
	if m != nil {
		return m.Itemid
	}
	return 0
}

func (m *LogUseitem) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *LogUseitem) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *LogUseitem) GetReason() int32 {
	if m != nil {
		return m.Reason
	}
	return 0
}

func (m *LogUseitem) GetRealid() int64 {
	if m != nil {
		return m.Realid
	}
	return 0
}

func (m *LogUseitem) GetTime() int32 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *LogUseitem) GetChange() int32 {
	if m != nil {
		return m.Change
	}
	return 0
}

func (m *LogUseitem) GetParam() int32 {
	if m != nil {
		return m.Param
	}
	return 0
}

type LogDraw struct {
	Cid                  int32    `protobuf:"varint,1,opt,name=cid,proto3" json:"cid,omitempty"`
	ItemId               int32    `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ItemType             int32    `protobuf:"varint,3,opt,name=item_type,json=itemType,proto3" json:"item_type,omitempty"`
	Num                  int32    `protobuf:"varint,4,opt,name=num,proto3" json:"num,omitempty"`
	Active               int32    `protobuf:"varint,5,opt,name=active,proto3" json:"active,omitempty"`
	Time                 int32    `protobuf:"varint,6,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogDraw) Reset()         { *m = LogDraw{} }
func (m *LogDraw) String() string { return proto.CompactTextString(m) }
func (*LogDraw) ProtoMessage()    {}
func (*LogDraw) Descriptor() ([]byte, []int) {
	return fileDescriptor_88e703bb8c3f1871, []int{31}
}

func (m *LogDraw) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogDraw.Unmarshal(m, b)
}
func (m *LogDraw) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogDraw.Marshal(b, m, deterministic)
}
func (m *LogDraw) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogDraw.Merge(m, src)
}
func (m *LogDraw) XXX_Size() int {
	return xxx_messageInfo_LogDraw.Size(m)
}
func (m *LogDraw) XXX_DiscardUnknown() {
	xxx_messageInfo_LogDraw.DiscardUnknown(m)
}

var xxx_messageInfo_LogDraw proto.InternalMessageInfo

func (m *LogDraw) GetCid() int32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

func (m *LogDraw) GetItemId() int32 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *LogDraw) GetItemType() int32 {
	if m != nil {
		return m.ItemType
	}
	return 0
}

func (m *LogDraw) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *LogDraw) GetActive() int32 {
	if m != nil {
		return m.Active
	}
	return 0
}

func (m *LogDraw) GetTime() int32 {
	if m != nil {
		return m.Time
	}
	return 0
}

type LogCurrency struct {
	Cid                  int32    `protobuf:"varint,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Ctype                int32    `protobuf:"varint,2,opt,name=ctype,proto3" json:"ctype,omitempty"`
	Change               int32    `protobuf:"varint,3,opt,name=change,proto3" json:"change,omitempty"`
	Num                  int32    `protobuf:"varint,4,opt,name=num,proto3" json:"num,omitempty"`
	Time                 int32    `protobuf:"varint,5,opt,name=time,proto3" json:"time,omitempty"`
	Reason               int32    `protobuf:"varint,6,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogCurrency) Reset()         { *m = LogCurrency{} }
func (m *LogCurrency) String() string { return proto.CompactTextString(m) }
func (*LogCurrency) ProtoMessage()    {}
func (*LogCurrency) Descriptor() ([]byte, []int) {
	return fileDescriptor_88e703bb8c3f1871, []int{32}
}

func (m *LogCurrency) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogCurrency.Unmarshal(m, b)
}
func (m *LogCurrency) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogCurrency.Marshal(b, m, deterministic)
}
func (m *LogCurrency) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogCurrency.Merge(m, src)
}
func (m *LogCurrency) XXX_Size() int {
	return xxx_messageInfo_LogCurrency.Size(m)
}
func (m *LogCurrency) XXX_DiscardUnknown() {
	xxx_messageInfo_LogCurrency.DiscardUnknown(m)
}

var xxx_messageInfo_LogCurrency proto.InternalMessageInfo

func (m *LogCurrency) GetCid() int32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

func (m *LogCurrency) GetCtype() int32 {
	if m != nil {
		return m.Ctype
	}
	return 0
}

func (m *LogCurrency) GetChange() int32 {
	if m != nil {
		return m.Change
	}
	return 0
}

func (m *LogCurrency) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *LogCurrency) GetTime() int32 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *LogCurrency) GetReason() int32 {
	if m != nil {
		return m.Reason
	}
	return 0
}

type LogChat struct {
	Cid                  int32    `protobuf:"varint,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Tocid                int32    `protobuf:"varint,2,opt,name=tocid,proto3" json:"tocid,omitempty"`
	Channel              int32    `protobuf:"varint,3,opt,name=channel,proto3" json:"channel,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Time                 int32    `protobuf:"varint,5,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogChat) Reset()         { *m = LogChat{} }
func (m *LogChat) String() string { return proto.CompactTextString(m) }
func (*LogChat) ProtoMessage()    {}
func (*LogChat) Descriptor() ([]byte, []int) {
	return fileDescriptor_88e703bb8c3f1871, []int{33}
}

func (m *LogChat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogChat.Unmarshal(m, b)
}
func (m *LogChat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogChat.Marshal(b, m, deterministic)
}
func (m *LogChat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogChat.Merge(m, src)
}
func (m *LogChat) XXX_Size() int {
	return xxx_messageInfo_LogChat.Size(m)
}
func (m *LogChat) XXX_DiscardUnknown() {
	xxx_messageInfo_LogChat.DiscardUnknown(m)
}

var xxx_messageInfo_LogChat proto.InternalMessageInfo

func (m *LogChat) GetCid() int32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

func (m *LogChat) GetTocid() int32 {
	if m != nil {
		return m.Tocid
	}
	return 0
}

func (m *LogChat) GetChannel() int32 {
	if m != nil {
		return m.Channel
	}
	return 0
}

func (m *LogChat) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *LogChat) GetTime() int32 {
	if m != nil {
		return m.Time
	}
	return 0
}

type LogLoginout struct {
	Cid                  int32    `protobuf:"varint,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Type                 int32    `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Ip                   string   `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	Time                 string   `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogLoginout) Reset()         { *m = LogLoginout{} }
func (m *LogLoginout) String() string { return proto.CompactTextString(m) }
func (*LogLoginout) ProtoMessage()    {}
func (*LogLoginout) Descriptor() ([]byte, []int) {
	return fileDescriptor_88e703bb8c3f1871, []int{34}
}

func (m *LogLoginout) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogLoginout.Unmarshal(m, b)
}
func (m *LogLoginout) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogLoginout.Marshal(b, m, deterministic)
}
func (m *LogLoginout) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogLoginout.Merge(m, src)
}
func (m *LogLoginout) XXX_Size() int {
	return xxx_messageInfo_LogLoginout.Size(m)
}
func (m *LogLoginout) XXX_DiscardUnknown() {
	xxx_messageInfo_LogLoginout.DiscardUnknown(m)
}

var xxx_messageInfo_LogLoginout proto.InternalMessageInfo

func (m *LogLoginout) GetCid() int32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

func (m *LogLoginout) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *LogLoginout) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *LogLoginout) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func init() {
	proto.RegisterType((*DBPlayerNumInfo)(nil), "LPMsg.DB_player_num_info")
	proto.RegisterType((*DBAccount)(nil), "LPMsg.DB_account")
	proto.RegisterType((*DBAccountLoad)(nil), "LPMsg.DB_account_load")
	proto.RegisterType((*DBAllRoleLevel)(nil), "LPMsg.DB_all_role_level")
	proto.RegisterType((*DBBanUid)(nil), "LPMsg.DB_ban_uid")
	proto.RegisterType((*DBBanIp)(nil), "LPMsg.DB_ban_ip")
	proto.RegisterType((*DBIpUnlimit)(nil), "LPMsg.DB_ip_unlimit")
	proto.RegisterType((*DBBanInfo)(nil), "LPMsg.DB_ban_info")
	proto.RegisterType((*DBRoleList)(nil), "LPMsg.DB_roleList")
	proto.RegisterType((*DBPlayer)(nil), "LPMsg.DB_player")
	proto.RegisterType((*DBChrItem)(nil), "LPMsg.DB_chr_item")
	proto.RegisterType((*DBChrRecord)(nil), "LPMsg.DB_chr_record")
	proto.RegisterType((*DBChrHero)(nil), "LPMsg.DB_chr_hero")
	proto.RegisterType((*DBChrDungeon)(nil), "LPMsg.DB_chr_dungeon")
	proto.RegisterType((*DBChrShopLimit)(nil), "LPMsg.DB_chr_shop_limit")
	proto.RegisterType((*DBChrBattleData)(nil), "LPMsg.DB_chr_battle_data")
	proto.RegisterType((*DBChrTask)(nil), "LPMsg.DB_chr_task")
	proto.RegisterType((*DBChrAchievement)(nil), "LPMsg.DB_chr_achievement")
	proto.RegisterType((*DBChrMail)(nil), "LPMsg.DB_chr_mail")
	proto.RegisterType((*DBChrServerMail)(nil), "LPMsg.DB_chr_server_mail")
	proto.RegisterType((*DBChrHeroTeam)(nil), "LPMsg.DB_chr_hero_team")
	proto.RegisterType((*DBChrClientRecord)(nil), "LPMsg.DB_chr_client_record")
	proto.RegisterType((*DBChrRelation)(nil), "LPMsg.DB_chr_relation")
	proto.RegisterType((*DBRelationList)(nil), "LPMsg.DB_relation_list")
	proto.RegisterType((*DBPlayerAllData)(nil), "LPMsg.DB_player_all_data")
	proto.RegisterType((*DBServerMail)(nil), "LPMsg.DB_server_mail")
	proto.RegisterType((*MailList)(nil), "LPMsg.MailList")
	proto.RegisterType((*DBSqlData)(nil), "LPMsg.DB_sql_data")
	proto.RegisterType((*DBSqlDataList)(nil), "LPMsg.DB_sql_data_list")
	proto.RegisterType((*DbPlayerMsg)(nil), "LPMsg.db_player_msg")
	proto.RegisterType((*LogUseitem)(nil), "LPMsg.log_useitem")
	proto.RegisterType((*LogDraw)(nil), "LPMsg.log_draw")
	proto.RegisterType((*LogCurrency)(nil), "LPMsg.log_currency")
	proto.RegisterType((*LogChat)(nil), "LPMsg.log_chat")
	proto.RegisterType((*LogLoginout)(nil), "LPMsg.log_loginout")
}

func init() { proto.RegisterFile("dbdata.proto", fileDescriptor_88e703bb8c3f1871) }

var fileDescriptor_88e703bb8c3f1871 = []byte{
	// 1876 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x58, 0x5f, 0x8f, 0xdc, 0x48,
	0x11, 0x97, 0xe7, 0xbf, 0x6b, 0x76, 0x93, 0x8d, 0xd9, 0xcb, 0xf9, 0x2e, 0x07, 0x97, 0x33, 0x22,
	0xda, 0x03, 0x14, 0xb4, 0x33, 0x09, 0x48, 0x20, 0x21, 0x14, 0x05, 0xa1, 0x70, 0xc9, 0x09, 0x35,
	0x8b, 0x84, 0x84, 0x90, 0xd5, 0x33, 0xee, 0xcc, 0xb6, 0xe2, 0x7f, 0x67, 0xf7, 0x6c, 0xb2, 0x7c,
	0x01, 0x5e, 0x78, 0xe0, 0x01, 0x09, 0xf1, 0xc8, 0x2b, 0x9f, 0xe0, 0xc4, 0x97, 0xe0, 0x43, 0xf0,
	0x04, 0x9f, 0x02, 0x55, 0x75, 0xb5, 0xed, 0x99, 0xf1, 0x9e, 0x16, 0xe9, 0xde, 0xfa, 0x57, 0x55,
	0xdd, 0xae, 0xae, 0xff, 0x6d, 0x38, 0x4a, 0x56, 0x89, 0x34, 0xf2, 0x71, 0x59, 0x15, 0xa6, 0x08,
	0xc6, 0x2f, 0x7f, 0xf5, 0xaa, 0xde, 0x7c, 0x18, 0x10, 0x8a, 0xd7, 0x45, 0x96, 0x15, 0xb9, 0x65,
	0x45, 0x6f, 0x21, 0x78, 0xfe, 0x2c, 0x2e, 0x53, 0x79, 0xad, 0xaa, 0x38, 0xdf, 0x66, 0xb1, 0xce,
	0x5f, 0x17, 0x41, 0x00, 0xa3, 0x64, 0xa5, 0x93, 0xd0, 0x7b, 0xe8, 0x9d, 0x8d, 0x05, 0xad, 0x83,
	0x13, 0x18, 0xe6, 0xdb, 0x2c, 0x1c, 0x10, 0x09, 0x97, 0xc1, 0x7d, 0x98, 0x64, 0xf2, 0x1d, 0x12,
	0x87, 0x44, 0x64, 0x14, 0x7c, 0x1b, 0x8e, 0xe5, 0x7a, 0x5d, 0x6c, 0x73, 0x13, 0x1b, 0xb9, 0x4a,
	0x55, 0x38, 0x22, 0xf6, 0x11, 0x13, 0x2f, 0x90, 0x16, 0xfd, 0xd5, 0x03, 0x78, 0xfe, 0x2c, 0x66,
	0x5a, 0xf0, 0x09, 0x1c, 0x95, 0xa9, 0x34, 0xaf, 0x8b, 0x2a, 0x8b, 0xb7, 0xfc, 0x65, 0x5f, 0xcc,
	0x1d, 0xed, 0x37, 0x3a, 0x09, 0x3e, 0x80, 0xd9, 0x46, 0x66, 0x8a, 0xd8, 0x56, 0x8b, 0x29, 0x62,
	0x64, 0x7d, 0x0c, 0xf3, 0x75, 0xa5, 0xa4, 0x51, 0xb1, 0xd1, 0x99, 0x62, 0x75, 0xc0, 0x92, 0x2e,
	0x74, 0xa6, 0x82, 0x3b, 0x30, 0xd0, 0x25, 0xe9, 0xe1, 0x8b, 0x81, 0x2e, 0x83, 0x0f, 0x61, 0xb6,
	0xd5, 0xc9, 0xa6, 0x2a, 0xb6, 0x65, 0x38, 0x26, 0xe9, 0x06, 0x47, 0x35, 0xdc, 0x6d, 0x15, 0x8b,
	0xd3, 0x42, 0x26, 0xc1, 0x12, 0xa6, 0xf9, 0x36, 0x43, 0xd3, 0x84, 0xde, 0xc3, 0xe1, 0xd9, 0x7c,
	0xf1, 0xc1, 0x63, 0x32, 0xe9, 0xe3, 0x43, 0xdb, 0x09, 0x27, 0x19, 0x7c, 0x0f, 0xa6, 0x7c, 0x48,
	0x38, 0xa0, 0x4d, 0xf7, 0xda, 0x4d, 0xcc, 0x10, 0x4e, 0x22, 0xfa, 0x9b, 0x07, 0xf7, 0x90, 0x9e,
	0xa6, 0x71, 0x55, 0xa4, 0x2a, 0x4e, 0xd5, 0x95, 0x4a, 0x6f, 0x63, 0x95, 0x10, 0xa6, 0x69, 0xb1,
	0xd1, 0x79, 0x6b, 0x14, 0x86, 0xc1, 0x29, 0x8c, 0xe9, 0x14, 0x36, 0x87, 0x05, 0x68, 0xaa, 0xb4,
	0xd8, 0x14, 0x5b, 0x63, 0x4d, 0x65, 0x5d, 0x03, 0x96, 0x44, 0xa6, 0x3a, 0x81, 0xe1, 0x5a, 0x27,
	0x6c, 0x15, 0x5c, 0x46, 0x2f, 0xc8, 0x53, 0x2b, 0x99, 0xa3, 0x0e, 0xb7, 0xd4, 0x49, 0xe5, 0x09,
	0x9d, 0xcf, 0x3a, 0x31, 0x8c, 0x1e, 0x80, 0xcf, 0x47, 0xe9, 0x92, 0x9d, 0xe2, 0x39, 0xa7, 0x44,
	0x4f, 0xe1, 0xf8, 0xf9, 0xb3, 0x58, 0x97, 0xf1, 0x36, 0x4f, 0x75, 0xa6, 0xcd, 0xbe, 0x00, 0xde,
	0x48, 0x97, 0x2a, 0xb7, 0x37, 0xf5, 0x85, 0x05, 0xd1, 0x5f, 0x3c, 0x98, 0xbb, 0x43, 0xd1, 0xee,
	0x9f, 0xc2, 0x64, 0x25, 0x73, 0xab, 0xda, 0x9e, 0xd9, 0xf9, 0x0e, 0x82, 0x05, 0x82, 0x47, 0x30,
	0x5e, 0xc9, 0x5c, 0x97, 0xec, 0xa0, 0x93, 0x5d, 0x49, 0x5d, 0x0a, 0xcb, 0x0e, 0x16, 0xe0, 0xb3,
	0x4e, 0xba, 0x0c, 0x87, 0x24, 0x7b, 0xda, 0xca, 0xb6, 0x1a, 0x8b, 0x56, 0x2c, 0xfa, 0x8c, 0xb4,
	0x42, 0x67, 0xbe, 0xd4, 0xb5, 0xc1, 0x4f, 0xe1, 0xba, 0x66, 0xa5, 0x4e, 0xf6, 0x03, 0x48, 0x58,
	0x36, 0xdd, 0x71, 0xb9, 0x48, 0x53, 0x52, 0x69, 0x2c, 0x2c, 0x88, 0xfe, 0x3e, 0x20, 0xc3, 0x59,
	0x51, 0xe7, 0x22, 0xaf, 0x71, 0x11, 0x52, 0xda, 0xb4, 0xc0, 0x25, 0xa6, 0x70, 0x2e, 0x39, 0x17,
	0x7c, 0x41, 0xeb, 0x36, 0x22, 0x46, 0xdd, 0x88, 0x08, 0x60, 0xb4, 0x29, 0x52, 0xe7, 0x71, 0x5a,
	0x07, 0xdf, 0x04, 0xa0, 0x30, 0xb2, 0x41, 0x32, 0x21, 0x8e, 0x4f, 0x14, 0x8a, 0x91, 0xbd, 0x20,
	0x9a, 0x1e, 0x04, 0xd1, 0x5e, 0x42, 0xce, 0x0e, 0x12, 0xf2, 0x04, 0x86, 0xea, 0x5d, 0x19, 0xfa,
	0x56, 0x61, 0xf5, 0xae, 0x3c, 0x88, 0x2b, 0x38, 0x8c, 0xab, 0x8f, 0xc0, 0xaf, 0xf5, 0x26, 0x97,
	0x66, 0x5b, 0xa9, 0x70, 0x4e, 0xfc, 0x96, 0x10, 0xc5, 0x64, 0xf0, 0xf5, 0x65, 0x15, 0x6b, 0xa3,
	0xb2, 0x1e, 0x23, 0xdd, 0x87, 0x09, 0x72, 0x1a, 0x3b, 0x31, 0x72, 0x95, 0x6d, 0xd8, 0x56, 0x36,
	0x74, 0x42, 0x9d, 0xab, 0xb7, 0xce, 0x50, 0x04, 0xa2, 0xcf, 0x28, 0x3e, 0xf1, 0x03, 0x95, 0x5a,
	0x17, 0x55, 0xd2, 0xf3, 0x89, 0x00, 0x46, 0xe6, 0xba, 0x74, 0x61, 0x4f, 0x6b, 0x3c, 0xec, 0x4a,
	0xa6, 0x5b, 0x57, 0x96, 0x2c, 0x88, 0xbe, 0x1c, 0x36, 0xea, 0x5e, 0xaa, 0xaa, 0xe8, 0x57, 0x17,
	0x39, 0xad, 0xba, 0x16, 0xdd, 0x90, 0xd7, 0x6c, 0xd0, 0x51, 0x6b, 0xd0, 0x00, 0x46, 0xb5, 0x91,
	0x95, 0xf3, 0x2b, 0xae, 0xb1, 0xee, 0xd5, 0x6f, 0x74, 0x9a, 0xa6, 0x57, 0xe7, 0xec, 0xd5, 0x06,
	0x77, 0x78, 0x0b, 0xf6, 0x68, 0x83, 0x3b, 0xbc, 0x25, 0x3b, 0xb3, 0xc1, 0x1d, 0xde, 0x13, 0xf6,
	0x67, 0x83, 0x51, 0xd7, 0xa2, 0x4a, 0x54, 0x45, 0xde, 0x1c, 0x0b, 0x0b, 0xf0, 0x66, 0x46, 0xa6,
	0x2a, 0x37, 0xe4, 0xc4, 0xb1, 0x60, 0x84, 0x74, 0xf5, 0xc5, 0x56, 0x97, 0xe7, 0xe1, 0xdd, 0x87,
	0xde, 0xd9, 0x50, 0x30, 0x6a, 0xe8, 0x8b, 0xf0, 0xa4, 0x43, 0x5f, 0x34, 0xf4, 0x65, 0x78, 0xaf,
	0x43, 0x5f, 0x52, 0x44, 0xab, 0xec, 0x3c, 0x0c, 0x88, 0x4a, 0x6b, 0xa6, 0x2d, 0xc2, 0x6f, 0x34,
	0xb4, 0x05, 0xd3, 0x96, 0xe1, 0x69, 0x43, 0x5b, 0x62, 0x18, 0x5a, 0x6d, 0x62, 0xba, 0x44, 0xf8,
	0x9e, 0x0d, 0x43, 0x4b, 0xfb, 0x35, 0x92, 0xa2, 0x2f, 0x3d, 0xb8, 0xc3, 0xae, 0x4b, 0xb6, 0xf9,
	0x46, 0x15, 0x79, 0x8f, 0xf7, 0xb0, 0x76, 0x39, 0xcf, 0x0d, 0x6c, 0x64, 0x90, 0x37, 0x86, 0x1d,
	0x6f, 0x7c, 0x02, 0x47, 0xaf, 0x75, 0x55, 0x9b, 0xb8, 0x52, 0x6f, 0x65, 0x95, 0xb0, 0xf3, 0xe6,
	0x44, 0x13, 0x44, 0x42, 0x03, 0x66, 0x45, 0xd9, 0x74, 0x29, 0x0b, 0x30, 0x3d, 0x69, 0xb1, 0x93,
	0x9e, 0x44, 0xa1, 0xe4, 0x0a, 0xb1, 0xf3, 0x5c, 0x6a, 0x75, 0xe5, 0x52, 0xd3, 0xc1, 0xe8, 0x8f,
	0xb6, 0xcd, 0xa0, 0xea, 0xf5, 0x65, 0x51, 0xc6, 0xb6, 0xce, 0x1e, 0x6a, 0xff, 0x3e, 0x4c, 0x89,
	0xdf, 0x06, 0x1f, 0xc2, 0x17, 0xa4, 0x8f, 0x6d, 0x69, 0x1c, 0x7c, 0xb6, 0x7b, 0x63, 0xb9, 0xc0,
	0x93, 0x62, 0x0a, 0xfe, 0x11, 0x97, 0x0b, 0xa4, 0x5c, 0x60, 0x06, 0x60, 0x56, 0xa0, 0xa2, 0x1c,
	0x89, 0xd4, 0x09, 0xfe, 0xe1, 0xd1, 0xe4, 0x81, 0x9a, 0xac, 0xa4, 0x31, 0xa9, 0x8a, 0x71, 0x60,
	0xe9, 0x51, 0x05, 0x73, 0x31, 0x4f, 0xd4, 0x3b, 0x56, 0xc4, 0x82, 0xe6, 0xc8, 0x61, 0x7b, 0x24,
	0x06, 0xe2, 0xba, 0xc8, 0xca, 0x4a, 0xd5, 0x35, 0xeb, 0xd0, 0x60, 0x0c, 0x95, 0xa2, 0xda, 0xa4,
	0x2a, 0x67, 0x25, 0x18, 0xd1, 0xa4, 0x23, 0x8d, 0x24, 0x1b, 0x1e, 0x89, 0x91, 0xd3, 0x21, 0x4b,
	0x9e, 0x92, 0xe9, 0x7c, 0x81, 0xcb, 0xe8, 0x77, 0x4d, 0xae, 0x1a, 0x59, 0xbf, 0xb9, 0x85, 0xb7,
	0x7b, 0x73, 0x1e, 0xa9, 0xb5, 0x91, 0xc6, 0x59, 0xc8, 0x82, 0x68, 0xd5, 0x18, 0x82, 0xbd, 0x94,
	0x61, 0x2e, 0x7c, 0xbd, 0xdf, 0xf8, 0x8f, 0xd7, 0xdc, 0x20, 0x93, 0x3a, 0xe5, 0xb3, 0x3c, 0x8a,
	0xfb, 0x81, 0x6e, 0x2a, 0xd9, 0x60, 0xa7, 0xfa, 0xd4, 0x2a, 0xc7, 0xd4, 0xb5, 0x1d, 0x84, 0x11,
	0x9e, 0x6f, 0xb4, 0xe1, 0xa1, 0xce, 0x17, 0x16, 0x60, 0xc4, 0xad, 0x8b, 0xdc, 0x60, 0x4a, 0x8f,
	0x89, 0xee, 0x20, 0x9e, 0xc3, 0xd1, 0x3d, 0xb1, 0xe7, 0x54, 0x4d, 0x60, 0x5b, 0x3d, 0xa7, 0x1d,
	0x3d, 0xad, 0xb4, 0xac, 0x8b, 0x9c, 0xab, 0x0c, 0xa3, 0xc6, 0xdd, 0x7e, 0xc7, 0xdd, 0x34, 0x7e,
	0xea, 0x94, 0x5b, 0x05, 0x8d, 0x9f, 0x88, 0xa2, 0x5f, 0x36, 0xf6, 0xac, 0x55, 0x75, 0xa5, 0xf8,
	0xc6, 0xb7, 0xca, 0xd0, 0xfd, 0x90, 0x8a, 0xfe, 0xe9, 0xc1, 0x49, 0xa7, 0x4a, 0xc7, 0x46, 0xc9,
	0xec, 0xd6, 0x31, 0x7a, 0x02, 0x43, 0x9d, 0x9c, 0xbb, 0xbe, 0xa2, 0x93, 0x73, 0x4b, 0x59, 0xb8,
	0x22, 0xad, 0x93, 0x85, 0xa5, 0x2c, 0xdd, 0xb4, 0xa5, 0x93, 0xa5, 0xa5, 0x3c, 0xe1, 0xa4, 0xc6,
	0xa5, 0xa5, 0x3c, 0x65, 0x43, 0xe1, 0xd2, 0x52, 0x7e, 0xc8, 0x36, 0xc2, 0x65, 0xd3, 0xee, 0xfd,
	0xb6, 0xdd, 0x47, 0x9f, 0xc3, 0x29, 0xeb, 0xbe, 0x4e, 0x35, 0x56, 0xb4, 0x1b, 0xdb, 0xd6, 0xad,
	0x42, 0x2b, 0xfa, 0xaf, 0x47, 0x93, 0xb1, 0x6d, 0x80, 0xa9, 0x34, 0xba, 0xb7, 0xf0, 0x61, 0x80,
	0x14, 0x6d, 0x30, 0x59, 0xd0, 0x34, 0xc6, 0x61, 0xa7, 0x31, 0x3a, 0x83, 0x8f, 0x3a, 0x4e, 0xfd,
	0x08, 0x7c, 0x1b, 0x20, 0x1b, 0x65, 0xd8, 0x2a, 0x2d, 0x21, 0xf8, 0x16, 0x80, 0x05, 0x18, 0x8c,
	0x6c, 0xa2, 0x0e, 0xa5, 0xb1, 0xc2, 0xb4, 0x33, 0xf4, 0xec, 0xcd, 0x2a, 0xb3, 0x83, 0x59, 0xe5,
	0x14, 0xc6, 0x79, 0x61, 0x54, 0xcd, 0xb6, 0xb3, 0x20, 0xfa, 0x29, 0x39, 0xde, 0xdd, 0x33, 0x4e,
	0x71, 0x86, 0xfb, 0x2e, 0x17, 0x0b, 0x3b, 0xc2, 0xdd, 0x6f, 0x47, 0xb8, 0xae, 0x49, 0x6c, 0x11,
	0x89, 0xfe, 0x3d, 0xee, 0xbe, 0xac, 0x70, 0xae, 0xa7, 0xda, 0x72, 0x06, 0x13, 0x4b, 0x22, 0x93,
	0xf5, 0xcd, 0x81, 0xcc, 0x0f, 0x1e, 0xc1, 0x08, 0xe7, 0x13, 0x1e, 0x4d, 0x83, 0xdd, 0x8f, 0x21,
	0x47, 0x10, 0x3f, 0xf8, 0x3e, 0xa6, 0x0c, 0xfa, 0xf5, 0x70, 0x30, 0x6d, 0x47, 0x15, 0xc1, 0x32,
	0x78, 0x2a, 0x06, 0x72, 0x38, 0xea, 0x3b, 0x15, 0x39, 0x82, 0xf8, 0xc1, 0x0f, 0x60, 0xca, 0xbd,
	0x2d, 0x1c, 0x93, 0xe8, 0x7b, 0xbb, 0xa2, 0xcc, 0x14, 0x4e, 0x2a, 0xf8, 0x11, 0x40, 0xdb, 0x51,
	0xc2, 0x09, 0xed, 0x09, 0x77, 0xf7, 0xb4, 0x7c, 0xe1, 0xe3, 0xfa, 0x25, 0x35, 0x9f, 0x47, 0x30,
	0xc2, 0xa2, 0x1a, 0x4e, 0xfb, 0x34, 0x42, 0x8e, 0x20, 0x7e, 0xf0, 0x13, 0x98, 0x77, 0xea, 0x63,
	0x38, 0xdb, 0x7f, 0x87, 0xed, 0x15, 0x50, 0xd1, 0x95, 0xc6, 0x8f, 0x60, 0x15, 0x08, 0xfd, 0xbe,
	0x8f, 0x20, 0x47, 0x10, 0x3f, 0xf8, 0x31, 0xcc, 0x3b, 0x45, 0x23, 0x84, 0xbe, 0x8f, 0x74, 0x04,
	0x04, 0x58, 0xf0, 0x0a, 0xf7, 0x7e, 0x07, 0xc6, 0x34, 0x7f, 0x84, 0x73, 0xda, 0x75, 0x97, 0x77,
	0xbd, 0x52, 0xd9, 0xcf, 0x91, 0x2c, 0x2c, 0x37, 0xf8, 0x18, 0x86, 0x1b, 0x95, 0x85, 0x47, 0x24,
	0x74, 0xdc, 0x0a, 0xfd, 0x42, 0x65, 0x02, 0x39, 0xc1, 0x13, 0xf0, 0x9b, 0x5a, 0x13, 0x1e, 0x93,
	0xd8, 0xfb, 0x87, 0x7e, 0x22, 0xb6, 0x98, 0xe1, 0xf2, 0x02, 0x8b, 0xd2, 0xcf, 0xe0, 0x78, 0x27,
	0xcb, 0xc3, 0x3b, 0xb4, 0xf3, 0xc1, 0xee, 0xce, 0x1d, 0x11, 0x71, 0x64, 0xa1, 0xb0, 0xa1, 0xb1,
	0x80, 0x99, 0x8b, 0xe1, 0xf0, 0xee, 0x57, 0x46, 0x78, 0x23, 0x87, 0x6f, 0x2f, 0x1c, 0x85, 0xba,
	0x85, 0xb6, 0x6d, 0x2d, 0xb6, 0x96, 0xb4, 0x8d, 0x64, 0xd0, 0xdf, 0x48, 0x86, 0x37, 0x34, 0x92,
	0xd1, 0x4d, 0x8d, 0x64, 0xbc, 0xd3, 0x48, 0x5c, 0x15, 0x99, 0x74, 0xca, 0xf6, 0x53, 0x98, 0xa1,
	0x4b, 0xe8, 0xe1, 0xf5, 0xe9, 0x4e, 0xd2, 0x76, 0xc2, 0xb8, 0xeb, 0x47, 0x9b, 0xb3, 0xbf, 0xa7,
	0x26, 0x59, 0x7f, 0xc1, 0xb9, 0x8a, 0x1a, 0xd2, 0xff, 0x0b, 0x8f, 0x2b, 0x19, 0x02, 0xac, 0x78,
	0x45, 0x69, 0x5c, 0xab, 0x2c, 0x4a, 0x83, 0x1a, 0xbc, 0x51, 0xd7, 0x35, 0xe5, 0x9f, 0x2f, 0x68,
	0xdd, 0xcc, 0x15, 0xa3, 0x76, 0xae, 0x88, 0x3e, 0xa7, 0x92, 0xe2, 0x8e, 0xb7, 0x25, 0xe5, 0xb0,
	0x7e, 0x9e, 0xc1, 0x18, 0xd9, 0xf5, 0x61, 0xe2, 0xbb, 0x9d, 0xc2, 0x0a, 0xe0, 0x7b, 0x39, 0x59,
	0xb9, 0x0a, 0x93, 0xd5, 0x9b, 0xfe, 0xf7, 0x08, 0xa9, 0x31, 0xe8, 0xa8, 0xf1, 0x2f, 0x8f, 0x2a,
	0x62, 0xbc, 0xad, 0xd5, 0xff, 0xf9, 0x50, 0xea, 0x2b, 0xe2, 0xfc, 0x78, 0x1a, 0xed, 0xfc, 0x16,
	0xe2, 0x1e, 0x3e, 0xde, 0xe9, 0xe1, 0x96, 0x8e, 0xfd, 0x7a, 0x62, 0xa7, 0x75, 0x8b, 0x1a, 0x07,
	0x4e, 0x77, 0x7b, 0xfb, 0xfa, 0x52, 0xe6, 0x1b, 0x57, 0xaf, 0x19, 0xa1, 0x4b, 0x4a, 0x59, 0xc9,
	0x8c, 0x07, 0x01, 0x0b, 0xa2, 0x3f, 0x7b, 0x30, 0xc3, 0x1b, 0x25, 0x95, 0x7c, 0xdb, 0x3f, 0xcc,
	0xe2, 0x05, 0xe2, 0xdd, 0xfb, 0xbc, 0x48, 0x82, 0x07, 0xe0, 0x13, 0xa3, 0x73, 0xa9, 0x19, 0x12,
	0x2e, 0x6e, 0xbc, 0x98, 0x5c, 0x1b, 0x7d, 0xe5, 0x06, 0x59, 0x46, 0xbd, 0x11, 0xf8, 0x27, 0x0f,
	0x8e, 0x50, 0xa5, 0xf5, 0xb6, 0xaa, 0x54, 0xbe, 0xbe, 0xee, 0x6f, 0x94, 0xeb, 0xce, 0x63, 0xd1,
	0x82, 0xce, 0xcd, 0x87, 0x3b, 0x37, 0x3f, 0x54, 0xa7, 0x67, 0xaa, 0xee, 0xd8, 0x7e, 0xd2, 0xb5,
	0x7d, 0xf4, 0x07, 0x6b, 0xa0, 0xf5, 0xa5, 0x34, 0xb7, 0x6e, 0xd9, 0x98, 0x8a, 0x97, 0x32, 0xcf,
	0x9b, 0x97, 0xa6, 0x83, 0x5f, 0x91, 0xa4, 0x7d, 0x93, 0xfe, 0x6f, 0xad, 0x25, 0xe8, 0xef, 0x41,
	0xb1, 0x35, 0xb7, 0x7c, 0x35, 0xdb, 0x7f, 0x3f, 0xc3, 0xe6, 0xdf, 0x4f, 0x77, 0x58, 0xf0, 0xed,
	0xc9, 0xab, 0x09, 0xfd, 0xc3, 0x5c, 0xfe, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xa8, 0x17, 0x0a, 0x99,
	0xee, 0x14, 0x00, 0x00,
}
