// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto_common.proto

package LPMsg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Int32Value struct {
	Value                int32    `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Int32Value) Reset()         { *m = Int32Value{} }
func (m *Int32Value) String() string { return proto.CompactTextString(m) }
func (*Int32Value) ProtoMessage()    {}
func (*Int32Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_05bf5807c45a1c34, []int{0}
}

func (m *Int32Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Int32Value.Unmarshal(m, b)
}
func (m *Int32Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Int32Value.Marshal(b, m, deterministic)
}
func (m *Int32Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int32Value.Merge(m, src)
}
func (m *Int32Value) XXX_Size() int {
	return xxx_messageInfo_Int32Value.Size(m)
}
func (m *Int32Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Int32Value.DiscardUnknown(m)
}

var xxx_messageInfo_Int32Value proto.InternalMessageInfo

func (m *Int32Value) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Int64Value struct {
	Value                int64    `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Int64Value) Reset()         { *m = Int64Value{} }
func (m *Int64Value) String() string { return proto.CompactTextString(m) }
func (*Int64Value) ProtoMessage()    {}
func (*Int64Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_05bf5807c45a1c34, []int{1}
}

func (m *Int64Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Int64Value.Unmarshal(m, b)
}
func (m *Int64Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Int64Value.Marshal(b, m, deterministic)
}
func (m *Int64Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int64Value.Merge(m, src)
}
func (m *Int64Value) XXX_Size() int {
	return xxx_messageInfo_Int64Value.Size(m)
}
func (m *Int64Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Int64Value.DiscardUnknown(m)
}

var xxx_messageInfo_Int64Value proto.InternalMessageInfo

func (m *Int64Value) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type VEmpty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VEmpty) Reset()         { *m = VEmpty{} }
func (m *VEmpty) String() string { return proto.CompactTextString(m) }
func (*VEmpty) ProtoMessage()    {}
func (*VEmpty) Descriptor() ([]byte, []int) {
	return fileDescriptor_05bf5807c45a1c34, []int{2}
}

func (m *VEmpty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VEmpty.Unmarshal(m, b)
}
func (m *VEmpty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VEmpty.Marshal(b, m, deterministic)
}
func (m *VEmpty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VEmpty.Merge(m, src)
}
func (m *VEmpty) XXX_Size() int {
	return xxx_messageInfo_VEmpty.Size(m)
}
func (m *VEmpty) XXX_DiscardUnknown() {
	xxx_messageInfo_VEmpty.DiscardUnknown(m)
}

var xxx_messageInfo_VEmpty proto.InternalMessageInfo

type VString struct {
	Val                  string   `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VString) Reset()         { *m = VString{} }
func (m *VString) String() string { return proto.CompactTextString(m) }
func (*VString) ProtoMessage()    {}
func (*VString) Descriptor() ([]byte, []int) {
	return fileDescriptor_05bf5807c45a1c34, []int{3}
}

func (m *VString) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VString.Unmarshal(m, b)
}
func (m *VString) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VString.Marshal(b, m, deterministic)
}
func (m *VString) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VString.Merge(m, src)
}
func (m *VString) XXX_Size() int {
	return xxx_messageInfo_VString.Size(m)
}
func (m *VString) XXX_DiscardUnknown() {
	xxx_messageInfo_VString.DiscardUnknown(m)
}

var xxx_messageInfo_VString proto.InternalMessageInfo

func (m *VString) GetVal() string {
	if m != nil {
		return m.Val
	}
	return ""
}

type Int32Array struct {
	Data                 []int32  `protobuf:"varint,1,rep,packed,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Int32Array) Reset()         { *m = Int32Array{} }
func (m *Int32Array) String() string { return proto.CompactTextString(m) }
func (*Int32Array) ProtoMessage()    {}
func (*Int32Array) Descriptor() ([]byte, []int) {
	return fileDescriptor_05bf5807c45a1c34, []int{4}
}

func (m *Int32Array) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Int32Array.Unmarshal(m, b)
}
func (m *Int32Array) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Int32Array.Marshal(b, m, deterministic)
}
func (m *Int32Array) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int32Array.Merge(m, src)
}
func (m *Int32Array) XXX_Size() int {
	return xxx_messageInfo_Int32Array.Size(m)
}
func (m *Int32Array) XXX_DiscardUnknown() {
	xxx_messageInfo_Int32Array.DiscardUnknown(m)
}

var xxx_messageInfo_Int32Array proto.InternalMessageInfo

func (m *Int32Array) GetData() []int32 {
	if m != nil {
		return m.Data
	}
	return nil
}

type Int64Array struct {
	Data                 []int64  `protobuf:"varint,1,rep,packed,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Int64Array) Reset()         { *m = Int64Array{} }
func (m *Int64Array) String() string { return proto.CompactTextString(m) }
func (*Int64Array) ProtoMessage()    {}
func (*Int64Array) Descriptor() ([]byte, []int) {
	return fileDescriptor_05bf5807c45a1c34, []int{5}
}

func (m *Int64Array) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Int64Array.Unmarshal(m, b)
}
func (m *Int64Array) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Int64Array.Marshal(b, m, deterministic)
}
func (m *Int64Array) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int64Array.Merge(m, src)
}
func (m *Int64Array) XXX_Size() int {
	return xxx_messageInfo_Int64Array.Size(m)
}
func (m *Int64Array) XXX_DiscardUnknown() {
	xxx_messageInfo_Int64Array.DiscardUnknown(m)
}

var xxx_messageInfo_Int64Array proto.InternalMessageInfo

func (m *Int64Array) GetData() []int64 {
	if m != nil {
		return m.Data
	}
	return nil
}

type StringArray struct {
	Data                 []string `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringArray) Reset()         { *m = StringArray{} }
func (m *StringArray) String() string { return proto.CompactTextString(m) }
func (*StringArray) ProtoMessage()    {}
func (*StringArray) Descriptor() ([]byte, []int) {
	return fileDescriptor_05bf5807c45a1c34, []int{6}
}

func (m *StringArray) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringArray.Unmarshal(m, b)
}
func (m *StringArray) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringArray.Marshal(b, m, deterministic)
}
func (m *StringArray) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringArray.Merge(m, src)
}
func (m *StringArray) XXX_Size() int {
	return xxx_messageInfo_StringArray.Size(m)
}
func (m *StringArray) XXX_DiscardUnknown() {
	xxx_messageInfo_StringArray.DiscardUnknown(m)
}

var xxx_messageInfo_StringArray proto.InternalMessageInfo

func (m *StringArray) GetData() []string {
	if m != nil {
		return m.Data
	}
	return nil
}

type Int32Pair struct {
	Data1                int32    `protobuf:"varint,1,opt,name=data1,proto3" json:"data1,omitempty"`
	Data2                int32    `protobuf:"varint,2,opt,name=data2,proto3" json:"data2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Int32Pair) Reset()         { *m = Int32Pair{} }
func (m *Int32Pair) String() string { return proto.CompactTextString(m) }
func (*Int32Pair) ProtoMessage()    {}
func (*Int32Pair) Descriptor() ([]byte, []int) {
	return fileDescriptor_05bf5807c45a1c34, []int{7}
}

func (m *Int32Pair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Int32Pair.Unmarshal(m, b)
}
func (m *Int32Pair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Int32Pair.Marshal(b, m, deterministic)
}
func (m *Int32Pair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int32Pair.Merge(m, src)
}
func (m *Int32Pair) XXX_Size() int {
	return xxx_messageInfo_Int32Pair.Size(m)
}
func (m *Int32Pair) XXX_DiscardUnknown() {
	xxx_messageInfo_Int32Pair.DiscardUnknown(m)
}

var xxx_messageInfo_Int32Pair proto.InternalMessageInfo

func (m *Int32Pair) GetData1() int32 {
	if m != nil {
		return m.Data1
	}
	return 0
}

func (m *Int32Pair) GetData2() int32 {
	if m != nil {
		return m.Data2
	}
	return 0
}

type Int32PairArray struct {
	Data                 []*Int32Pair `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Int32PairArray) Reset()         { *m = Int32PairArray{} }
func (m *Int32PairArray) String() string { return proto.CompactTextString(m) }
func (*Int32PairArray) ProtoMessage()    {}
func (*Int32PairArray) Descriptor() ([]byte, []int) {
	return fileDescriptor_05bf5807c45a1c34, []int{8}
}

func (m *Int32PairArray) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Int32PairArray.Unmarshal(m, b)
}
func (m *Int32PairArray) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Int32PairArray.Marshal(b, m, deterministic)
}
func (m *Int32PairArray) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int32PairArray.Merge(m, src)
}
func (m *Int32PairArray) XXX_Size() int {
	return xxx_messageInfo_Int32PairArray.Size(m)
}
func (m *Int32PairArray) XXX_DiscardUnknown() {
	xxx_messageInfo_Int32PairArray.DiscardUnknown(m)
}

var xxx_messageInfo_Int32PairArray proto.InternalMessageInfo

func (m *Int32PairArray) GetData() []*Int32Pair {
	if m != nil {
		return m.Data
	}
	return nil
}

type MemEquip struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Cid                  int32    `protobuf:"varint,2,opt,name=cid,proto3" json:"cid,omitempty"`
	Base                 int32    `protobuf:"varint,3,opt,name=base,proto3" json:"base,omitempty"`
	Heroid               int32    `protobuf:"varint,4,opt,name=heroid,proto3" json:"heroid,omitempty"`
	Level                int32    `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`
	Exp                  int32    `protobuf:"varint,6,opt,name=exp,proto3" json:"exp,omitempty"`
	Star                 int32    `protobuf:"varint,7,opt,name=star,proto3" json:"star,omitempty"`
	Lock                 int32    `protobuf:"varint,8,opt,name=lock,proto3" json:"lock,omitempty"`
	Isnew                int32    `protobuf:"varint,9,opt,name=isnew,proto3" json:"isnew,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MemEquip) Reset()         { *m = MemEquip{} }
func (m *MemEquip) String() string { return proto.CompactTextString(m) }
func (*MemEquip) ProtoMessage()    {}
func (*MemEquip) Descriptor() ([]byte, []int) {
	return fileDescriptor_05bf5807c45a1c34, []int{9}
}

func (m *MemEquip) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemEquip.Unmarshal(m, b)
}
func (m *MemEquip) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemEquip.Marshal(b, m, deterministic)
}
func (m *MemEquip) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemEquip.Merge(m, src)
}
func (m *MemEquip) XXX_Size() int {
	return xxx_messageInfo_MemEquip.Size(m)
}
func (m *MemEquip) XXX_DiscardUnknown() {
	xxx_messageInfo_MemEquip.DiscardUnknown(m)
}

var xxx_messageInfo_MemEquip proto.InternalMessageInfo

func (m *MemEquip) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MemEquip) GetCid() int32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

func (m *MemEquip) GetBase() int32 {
	if m != nil {
		return m.Base
	}
	return 0
}

func (m *MemEquip) GetHeroid() int32 {
	if m != nil {
		return m.Heroid
	}
	return 0
}

func (m *MemEquip) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *MemEquip) GetExp() int32 {
	if m != nil {
		return m.Exp
	}
	return 0
}

func (m *MemEquip) GetStar() int32 {
	if m != nil {
		return m.Star
	}
	return 0
}

func (m *MemEquip) GetLock() int32 {
	if m != nil {
		return m.Lock
	}
	return 0
}

func (m *MemEquip) GetIsnew() int32 {
	if m != nil {
		return m.Isnew
	}
	return 0
}

type MemEquipList struct {
	Data                 []*MemEquip `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *MemEquipList) Reset()         { *m = MemEquipList{} }
func (m *MemEquipList) String() string { return proto.CompactTextString(m) }
func (*MemEquipList) ProtoMessage()    {}
func (*MemEquipList) Descriptor() ([]byte, []int) {
	return fileDescriptor_05bf5807c45a1c34, []int{10}
}

func (m *MemEquipList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemEquipList.Unmarshal(m, b)
}
func (m *MemEquipList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemEquipList.Marshal(b, m, deterministic)
}
func (m *MemEquipList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemEquipList.Merge(m, src)
}
func (m *MemEquipList) XXX_Size() int {
	return xxx_messageInfo_MemEquipList.Size(m)
}
func (m *MemEquipList) XXX_DiscardUnknown() {
	xxx_messageInfo_MemEquipList.DiscardUnknown(m)
}

var xxx_messageInfo_MemEquipList proto.InternalMessageInfo

func (m *MemEquipList) GetData() []*MemEquip {
	if m != nil {
		return m.Data
	}
	return nil
}

type MemGem struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Cid                  int32    `protobuf:"varint,2,opt,name=cid,proto3" json:"cid,omitempty"`
	Base                 int32    `protobuf:"varint,3,opt,name=base,proto3" json:"base,omitempty"`
	Heroid               int32    `protobuf:"varint,4,opt,name=heroid,proto3" json:"heroid,omitempty"`
	Level                int32    `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`
	Exp                  int32    `protobuf:"varint,6,opt,name=exp,proto3" json:"exp,omitempty"`
	Attr                 string   `protobuf:"bytes,7,opt,name=attr,proto3" json:"attr,omitempty"`
	Lock                 int32    `protobuf:"varint,8,opt,name=lock,proto3" json:"lock,omitempty"`
	Isnew                int32    `protobuf:"varint,9,opt,name=isnew,proto3" json:"isnew,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MemGem) Reset()         { *m = MemGem{} }
func (m *MemGem) String() string { return proto.CompactTextString(m) }
func (*MemGem) ProtoMessage()    {}
func (*MemGem) Descriptor() ([]byte, []int) {
	return fileDescriptor_05bf5807c45a1c34, []int{11}
}

func (m *MemGem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemGem.Unmarshal(m, b)
}
func (m *MemGem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemGem.Marshal(b, m, deterministic)
}
func (m *MemGem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemGem.Merge(m, src)
}
func (m *MemGem) XXX_Size() int {
	return xxx_messageInfo_MemGem.Size(m)
}
func (m *MemGem) XXX_DiscardUnknown() {
	xxx_messageInfo_MemGem.DiscardUnknown(m)
}

var xxx_messageInfo_MemGem proto.InternalMessageInfo

func (m *MemGem) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MemGem) GetCid() int32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

func (m *MemGem) GetBase() int32 {
	if m != nil {
		return m.Base
	}
	return 0
}

func (m *MemGem) GetHeroid() int32 {
	if m != nil {
		return m.Heroid
	}
	return 0
}

func (m *MemGem) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *MemGem) GetExp() int32 {
	if m != nil {
		return m.Exp
	}
	return 0
}

func (m *MemGem) GetAttr() string {
	if m != nil {
		return m.Attr
	}
	return ""
}

func (m *MemGem) GetLock() int32 {
	if m != nil {
		return m.Lock
	}
	return 0
}

func (m *MemGem) GetIsnew() int32 {
	if m != nil {
		return m.Isnew
	}
	return 0
}

type MemGemList struct {
	Data                 []*MemGem `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MemGemList) Reset()         { *m = MemGemList{} }
func (m *MemGemList) String() string { return proto.CompactTextString(m) }
func (*MemGemList) ProtoMessage()    {}
func (*MemGemList) Descriptor() ([]byte, []int) {
	return fileDescriptor_05bf5807c45a1c34, []int{12}
}

func (m *MemGemList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemGemList.Unmarshal(m, b)
}
func (m *MemGemList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemGemList.Marshal(b, m, deterministic)
}
func (m *MemGemList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemGemList.Merge(m, src)
}
func (m *MemGemList) XXX_Size() int {
	return xxx_messageInfo_MemGemList.Size(m)
}
func (m *MemGemList) XXX_DiscardUnknown() {
	xxx_messageInfo_MemGemList.DiscardUnknown(m)
}

var xxx_messageInfo_MemGemList proto.InternalMessageInfo

func (m *MemGemList) GetData() []*MemGem {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Int32Value)(nil), "LPMsg.Int32Value")
	proto.RegisterType((*Int64Value)(nil), "LPMsg.Int64Value")
	proto.RegisterType((*VEmpty)(nil), "LPMsg.VEmpty")
	proto.RegisterType((*VString)(nil), "LPMsg.VString")
	proto.RegisterType((*Int32Array)(nil), "LPMsg.Int32Array")
	proto.RegisterType((*Int64Array)(nil), "LPMsg.Int64Array")
	proto.RegisterType((*StringArray)(nil), "LPMsg.StringArray")
	proto.RegisterType((*Int32Pair)(nil), "LPMsg.Int32Pair")
	proto.RegisterType((*Int32PairArray)(nil), "LPMsg.Int32PairArray")
	proto.RegisterType((*MemEquip)(nil), "LPMsg.MemEquip")
	proto.RegisterType((*MemEquipList)(nil), "LPMsg.MemEquipList")
	proto.RegisterType((*MemGem)(nil), "LPMsg.MemGem")
	proto.RegisterType((*MemGemList)(nil), "LPMsg.MemGemList")
}

func init() { proto.RegisterFile("proto_common.proto", fileDescriptor_05bf5807c45a1c34) }

var fileDescriptor_05bf5807c45a1c34 = []byte{
	// 378 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x53, 0xcd, 0x6a, 0xc2, 0x40,
	0x18, 0x24, 0xc6, 0x44, 0xf3, 0xd9, 0x5a, 0x59, 0x4a, 0x59, 0xe8, 0x45, 0xd3, 0x1e, 0x3c, 0x59,
	0x1a, 0xc5, 0x9e, 0x7b, 0x10, 0x29, 0x28, 0x48, 0x0a, 0x5e, 0xcb, 0x6a, 0x16, 0xbb, 0x34, 0x7f,
	0xdd, 0xac, 0x56, 0xdf, 0xad, 0xf4, 0xd9, 0xca, 0xfe, 0x44, 0x2b, 0xf6, 0xd2, 0x53, 0x6f, 0x33,
	0xc3, 0x64, 0xbe, 0x99, 0x85, 0x00, 0xca, 0x79, 0x26, 0xb2, 0x97, 0x65, 0x96, 0x24, 0x59, 0xda,
	0x53, 0x04, 0x39, 0x93, 0xd9, 0xb4, 0x58, 0xf9, 0x3e, 0xc0, 0x53, 0x2a, 0xfa, 0xc1, 0x9c, 0xc4,
	0x6b, 0x8a, 0x2e, 0xc1, 0xd9, 0x48, 0x80, 0xad, 0xb6, 0xd5, 0x75, 0x42, 0x4d, 0x8c, 0x67, 0x38,
	0xf8, 0xc5, 0x63, 0x97, 0x9e, 0x3a, 0xb8, 0xf3, 0x51, 0x92, 0x8b, 0x9d, 0x7f, 0x0d, 0xb5, 0xf9,
	0xb3, 0xe0, 0x2c, 0x5d, 0xa1, 0x16, 0xd8, 0x1b, 0x12, 0x2b, 0xa3, 0x17, 0x4a, 0xe8, 0xb7, 0xcd,
	0xb9, 0x47, 0xce, 0xc9, 0x0e, 0x21, 0xa8, 0x46, 0x44, 0x10, 0x6c, 0xb5, 0xed, 0xae, 0x13, 0x2a,
	0x6c, 0x1c, 0xc3, 0xc1, 0xa9, 0xc3, 0x36, 0x8e, 0x0e, 0x34, 0x74, 0xfe, 0xa9, 0xc5, 0x33, 0x96,
	0x07, 0xf0, 0xd4, 0x99, 0x19, 0x61, 0x5c, 0x16, 0x96, 0xe2, 0x7d, 0x39, 0x4a, 0x91, 0x52, 0x0d,
	0x70, 0xe5, 0xa0, 0x06, 0xfe, 0x10, 0x9a, 0xfb, 0x0f, 0x75, 0xfc, 0xed, 0x8f, 0xf8, 0x46, 0xd0,
	0xea, 0xa9, 0x67, 0xeb, 0xed, 0x4d, 0xe6, 0xe0, 0x97, 0x05, 0xf5, 0x29, 0x4d, 0x46, 0xef, 0x6b,
	0x96, 0xa3, 0x26, 0x54, 0x58, 0x64, 0x9e, 0xa7, 0xc2, 0x22, 0xf9, 0x0c, 0x4b, 0x16, 0x99, 0x43,
	0x12, 0xca, 0xce, 0x0b, 0x52, 0x50, 0x6c, 0x2b, 0x49, 0x61, 0x74, 0x05, 0xee, 0x2b, 0xe5, 0x19,
	0x8b, 0x70, 0x55, 0xa9, 0x86, 0xc9, 0xa2, 0x31, 0xdd, 0xd0, 0x18, 0x3b, 0xba, 0xa8, 0x22, 0x32,
	0x93, 0x6e, 0x73, 0xec, 0xea, 0x4c, 0xba, 0xcd, 0x65, 0x66, 0x21, 0x08, 0xc7, 0x35, 0x9d, 0x29,
	0xb1, 0xd4, 0xe2, 0x6c, 0xf9, 0x86, 0xeb, 0x5a, 0x93, 0x58, 0xe6, 0xb1, 0x22, 0xa5, 0x1f, 0xd8,
	0xd3, 0x79, 0x8a, 0xf8, 0x7d, 0x38, 0x2b, 0xfb, 0x4f, 0x58, 0x21, 0xd0, 0xcd, 0xd1, 0xec, 0x0b,
	0x33, 0xbb, 0xb4, 0x98, 0xd5, 0x9f, 0x16, 0xb8, 0x53, 0x9a, 0x8c, 0x69, 0xf2, 0x7f, 0x9b, 0x89,
	0x10, 0x7a, 0xb3, 0x17, 0x2a, 0xfc, 0x87, 0xcd, 0x77, 0x00, 0xba, 0xbd, 0x5a, 0xdc, 0x39, 0x5a,
	0x7c, 0x7e, 0x58, 0x3c, 0xa6, 0x89, 0xde, 0xbb, 0x70, 0xd5, 0xaf, 0xd3, 0xff, 0x0e, 0x00, 0x00,
	0xff, 0xff, 0x32, 0x33, 0xbd, 0x60, 0x50, 0x03, 0x00, 0x00,
}
